### ISSUE TITLE
Allow users to leave comments

### ISSUE THREAD

**Issue by michael-lazar** [michael-lazar/rtv#10]
This one requires a bit of thought about how to input the text using a textbox.

**Comment by shanhind** [comment]
I'm going to take a shot at adding this feature.  I'm new to curses so this might take me a bit of time for learning so if anyone else already has curses experience and wants to take care of this just let me know so I don't continue working on it.  :)

**Comment by yskmt** [comment]
Ohh I just started testing/implementing it... 
Can I take care of it?
https://github.com/yskmt/rtv/commit/77c6d59ca02391edf939b7fa8c631e0dcfdc87c0

**Comment by shanhind** [comment]
Yep no problem.

**Comment by yskmt** [comment]
OK I implemented `add_comment` function. Right now it's only good for a one-line comment, but I am thinking I should create a message box in the middle of screen for commenting. What do you think?
https://github.com/michael-lazar/rtv/compare/master...yskmt:post-comment

I am also trying to implement `add_reply` function too. It seems much more difficult because I need to specify the object that I want to reply to.

**Comment by michael-lazar** [comment]
I would also try out splitting the screen in half and using the bottom half for the comment. That way you could get away with just a horizontal bar ``---------`` instead of a full box outline. For add reply, I think you could just select whichever comment the cursor is focused on. Something like
```python
content.get(cursor_position)['object'].add_reply()
```

Also, don't forget to check if the user is logged in before opening the textbox!

**Comment by yskmt** [comment]
I added the `reply` functionality too. Press `c` on the submission page and you can post some comment or reply to a comment.

There are a lot of rooms for improvements, such as:

1. Better `textbox` for editing comment.
2. Error handling.
3. Prompt to log in if you are not.
4. Refresh the page and jump to your comment after you post it.

3 and 4 should be implemented in different functions though.

**Comment by yskmt** [comment]
The comment box now occupies the bottom half of the terminal. However I found a bug in `curses`, in which I can only use overwrite-mode for `textbox`.

http://bugs.python.org/issue13051

**Comment by michael-lazar** [comment]
curses is just full of fun surprises!

**Comment by michael-lazar** [comment]
Merged in #38 

The current textpad has the following limitations:

1. Can't resize the window while entering text
2. Can't type characters in insert mode (http://bugs.python.org/issue13051)
3. Text doesn't scroll up when you reach the end of the textpad.

In the future we may want to look into an alternate solution (not curses) to handle text input for comments.

**Comment by noahmorrison** [comment]
How about using a temporary text file, and them opening it in your default editor ($EDITOR). The same way git does commit messages. This actually sounds decently easy to implement. And would allow the user to enter the text anyway they want.

Just a thought, might look into writing a pull request for it tomorrow. (I'm going to Boston, so it wouldn't be till late).

**Comment by michael-lazar** [comment]
Go for it, I think its a cool idea!

**Comment by yskmt** [comment]
I actually started writing some module that is intended to replace `curses.textpad` with more functionality such as page scrolling, loading text, refreshing on resize, etc. It is little buggy right now, but I'll let you know if it works out.
https://github.com/yskmt/texteditpad

**Comment by michael-lazar** [comment]
@yskmt keep me updated on this!

**Comment by yskmt** [comment]
@michael-lazar I might be late on this matter, but take a look on this pull request https://github.com/michael-lazar/rtv/pull/49
