### ISSUE TITLE
[Feature Request] Enter comments to directly open links in browser

### ISSUE THREAD

**Issue by TLATER** [michael-lazar/rtv#100]
Pretty much just as the title says, many comments also contain links and being unable to open those without looking for them in the comment section forces mouse usage.

**Comment by michael-lazar** [comment]
I agree that this would be a great thing to have. There are two parts to the problem.

1. We need to either find a builtin library function or build some custom regular expression to search for valid links in the comment bodies. I don't anticipate this being too difficult.
2. We need a way to handle comments that containmore than one link. How would you select which link to open? I would be hesitant to add new key bindings for this unless they were very intuitive.

**Comment by TLATER** [comment]
I'd suggest another mode that is accessible through submission mode. Accessing it would use right arrow, which folding currently uses. I guess folding could instead use enter, that appears more intuitive than right arrow to me (or vice-versa, but that would be inconsistent with the current keybindings).

In comment mode up and down select individual links, enter opens them, and left moves back to submission mode. There could even be more features, like instantly replying to the current comment, or showing the context.

If I dream on this might even be useful for implementing an inbox feature somewhere down the line.

**Comment by mrjovanovic** [comment]
Same should be valid for selfposts, which also often have URLs.

For the regex, [here](https://mathiasbynens.be/demo/url-regex) is an overview of different options. It seems that this one is probably the best for our purposes, as it fails on mistyped URLs:

`_^(?:(?:https?|ftp)://)(?:\S+(?::\S*)?@)?(?:(?!10(?:\.\d{1,3}){3})(?!127(?:\.\d{1,3}){3})(?!169\.254(?:\.\d{1,3}){2})(?!192\.168(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\x{00a1}-\x{ffff}0-9]+-?)*[a-z\x{00a1}-\x{ffff}0-9]+)(?:\.(?:[a-z\x{00a1}-\x{ffff}0-9]+-?)*[a-z\x{00a1}-\x{ffff}0-9]+)*(?:\.(?:[a-z\x{00a1}-\x{ffff}]{2,})))(?::\d{2,5})?(?:/[^\s]*)?$_iuS`

I think @TLATER's comment is a good way to implement this. Right arrow gets the comment, regex is run on that to get URLs, those are listed in a pop-up window (for example).

**Comment by zambonin** [comment]
I managed to do this with a smaller regex, and I do believe it works fine under our conditions.

I don't know curses well enough to produce something like selecting inside a box with up and down and pressing enter to confirm, so I managed to make the user access a link with the 1-9 keys.

If that happens, though, the approach would have to be changed...

![captura de tela de 2015-10-17 00-48-26](https://cloud.githubusercontent.com/assets/10156699/10556868/e46d209c-7468-11e5-973c-30d095114993.png)

**Comment by michael-lazar** [comment]
Merged. The approach ended up being a bit different than was discussed here, but the result should provide the same functionality.
