### ISSUE TITLE
When pressing enter on a specific comment, the original thread is opened.

### ISSUE THREAD

**Issue by Kirov123** [michael-lazar/rtv#102]
When pressing enter on a specific comment, could RTV open the permalink to the selected comment?

**Comment by michael-lazar** [comment]
I think that's a great idea, and shouldn't be too hard to implement. Pull requests are always welcome :wink:

**Comment by Brobin** [comment]
:+1: This is one step closer to #100, as it would get you the direct link to the comment to follow those links.

**Comment by michael-lazar** [comment]
Added in 71e464d03f2a7cfa9f5435d543bcb4ceab2cd216
