### ISSUE TITLE
subreddit jump list / tabs

### ISSUE THREAD

**Issue by gotbletu** [michael-lazar/rtv#104]
I dont like to waste time typing the subreddit everytime i want to switch.

Idea:
a way to bookmark all your favorite subreddit in the config.
Use a hotkey to see the list, then jump to the subreddit you want quickly.
Or add tabs support

**Comment by michael-lazar** [comment]
I've thought about this a bit myself as well. I think the best thing to do would be to display the user's subscribed subreddits. AFAIK this is Reddit's equivalent to "bookmarking". We can grab the list with praw's [get_my_subreddits](https://praw.readthedocs.org/en/v2.1.21/pages/code_overview.html#praw.__init__.MySubredditsMixin.get_my_subreddits) function. The tricky part will be displaying the list with curses and supporting stable scrolling. I'm all for it though! There's a large backlog of issues that I'm currently working through ATM. We're very open to contributions if you want to try putting something together.

**Comment by tobywhughes** [comment]
I could see something along the lines of when entering in the subreddit name, have a button that opens up a prompt that allows you to select your subscribed subreddits. If there are more than a certain amount, have a a key like [ and ] to select a different page. I don't really know much about curses, but I'll see if I can put something together.

Oh, and hi everybody! Haven't been able to contribute for a while cause of school and work, but just finished finals so I'll be around for a couple of weeks.

**Comment by michael-lazar** [comment]
Closing, as a similar feature is available through opening the user's subscriptions
