### ISSUE TITLE
Downvoting seems to have become broken.

### ISSUE THREAD

**Issue by mekhami** [michael-lazar/rtv#112]
When a submission is neutral (no upvotes or downvotes):
-I can upvote
-I cannot downvote

When a submission is upvoted:
-hitting 'z' turns the upvote into a downvote.

When a submission is downvoted:
-hitting 'z' turns the downvote into a neutral.

**Comment by michael-lazar** [comment]
There was a recent patch for downvoting that hasn't been released yet, https://github.com/michael-lazar/rtv/issues/108. Are you running off of the master branch?

**Comment by mekhami** [comment]
I'm running off master, is that patch merged into a different branch?

**Comment by michael-lazar** [comment]
Yea it should have been fixed in master. I checked and you're right, it's still not working correctly. Marking this as a bug.

**Comment by michael-lazar** [comment]
Ok I just fixed this in 9c75061. I tested out as many edge cases as I could and it looks like everything is working now. Thanks for the bug report, let me know if you find any more problems!
