### ISSUE TITLE
ResourceWarning and lost functionality.

### ISSUE THREAD

**Issue by mekhami** [michael-lazar/rtv#114]
```
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.173.113.69', 52014), raddr=('198.41.208.142', 443)>
/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py:2150: ImportWarning: sys.meta_path is empty
```
This is an error I got when i closed rtv, also some functions didn't seem to work like pressing i to check for unread messages.

**Comment by michael-lazar** [comment]
I looked into the ResourceWarning and it seems to be a common issue on python 3. I'll see if I can silence it, but it shouldn't cause any negative side effects for the time being. My guess is that the other issues you're seeing are unrelated. Can you elaborate any further?

**Comment by michael-lazar** [comment]
Fixed the ResourceWarning. 8eee962c6bc9fa1a740465ca105bdd82ce9b23cc
