### ISSUE TITLE
Newlines in self-texts and comments do not render

### ISSUE THREAD

**Issue by nicko-** [michael-lazar/rtv#12]
![](http://i.gyazo.com/b858f0ed8ffabbe0ebea29883238aaae.png)

As we can see in the screenshot above, it seems as if newlines are not rendered, causing the text to appear as a single paragraph. The post in the example above is https://www.reddit.com/r/Python/comments/2xrhq9/what_should_i_download_on_my_laptop_to_learn/.

I am using the git version as of revision 97d72a0 on Cygwin/Windows 8.1 with Python 3.2.5.

**Comment by tobywhughes** [comment]
I'm guessing this has something to do with the fact that it takes to newlines on reddit to display a single newline.

**Comment by snahor** [comment]
This is because `wrap` removes newlines. @michael-lazar if you want I can send you a pull request modifying this.

**Comment by michael-lazar** [comment]
@nicko thanks for the detailed bug report. @snahor a pull request would be great.
