### ISSUE TITLE
default open selfposts internally

### ISSUE THREAD

**Issue by obosob** [michael-lazar/rtv#121]
Essentially make the default behaviour for the [enter] or [o] key the same as the [L] key on selfposts. maybe introduce a new binding like [O] (capital o) for forcing it to open in the browser.

**Comment by michael-lazar** [comment]
See https://github.com/michael-lazar/rtv/issues/88.  At first I was hesitant to do this but I may be wrong. It's something that a few people have asked for now. I think the problem in general is that the README needs to be more clear on how the keybindings are laid out.

**Comment by obosob** [comment]
'o' certainly does map in my mind to 'open' as in, "open in browser" so i see your point about that having altering behaviour.

Just a thought though, maybe [Enter] could be mapped to something you could call "smart open" and attach the suggested behaviour to that.

As an example, if you look at any app for mobile devices,following a link to a submission will open the page in a browser (internel or external) but following the link for a selfpost opens in the app.

The intuitive behaviour is that the "go" action, whatever that may be, will do what makes sense with that object, selfposts are basically post with no link/where the link is to some reddit comments, this it makes sense that the default action on that is to open the comments in rtv.

**Comment by Brobin** [comment]
:+1: I think it makes more sense to open selfposts in the terminal. It is a weird transition to view comments in the browser, especially since you may not be logged in on the browser. It might look something like this.

[subreddit.py#94](https://github.com/michael-lazar/rtv/blob/master/rtv/subreddit.py#L94)

```python
    @SubredditController.register(curses.KEY_ENTER, 10, 'o')
    def open_link(self):
        "Open a link with the webbrowser, open selfposts in rtv"
        data = self.content.get(self.nav.absolute_index)
        if data['selfpost']:
            self.open_submission()
        else:
            url = data['url_full']
            open_browser(url)
            global history
            history.add(url)
```

**Comment by michael-lazar** [comment]
Go for it, Brobin.
