### ISSUE TITLE
Improper module

### ISSUE THREAD

**Issue by andyhills** [michael-lazar/rtv#134]
Traceback (most recent call last):
  File "/usr/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/lib/python2.7/site-packages/rtv/__main__.py", line 8, in <module>
    import praw
  File "/usr/lib/python2.7/site-packages/praw/__init__.py", line 47, in <module>
    from six.moves.urllib.parse import parse_qs, urlparse, urlunparse
ImportError: No module named urllib.parse

six.moves.urllib seems to exist in python3, not in python2.7
let me know if you want more info from my system

**Comment by michael-lazar** [comment]
You probably have an old version of six, try ``sudo pip install -U six``
Here's my installation for reference
```
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import six
>>> six.__version__
'1.9.0'
>>> import six.moves.urllib.parse
>>> 
```

**Comment by andyhills** [comment]
Thanks friend.
