### ISSUE TITLE
Authorizing oauth through a terminal web browser

### ISSUE THREAD

**Issue by michael-lazar** [michael-lazar/rtv#140]
The oauth flow doesn't work if your $BROWSER is set to something terminal based e.g. ``export BROWSER=w3m``. The loading dialog messes with the window

![image](https://cloud.githubusercontent.com/assets/5026795/9536656/3fb345f6-4ce3-11e5-91e8-a57c3b4cd79b.png)

And after you authorize the app, you get stuck here waiting for a reply

![image](https://cloud.githubusercontent.com/assets/5026795/9536709/f4521b54-4ce3-11e5-85dc-5b0fe3e6cdc8.png)

**Comment by michael-lazar** [comment]
Another point on this, I think we should use the mobile page that reddit provides. You can hack the URL by setting
```
reddit.config.API_PATHS['authorize'] += '.compact'
```
Here's what the difference looks like in the terminal for the login page

**https://www.reddit.com/login**
![image](https://cloud.githubusercontent.com/assets/5026795/9536779/e32a4fc6-4ce4-11e5-9ed0-b0c2c47e694c.png)

**https://www.reddit.com/login.compact**
![image](https://cloud.githubusercontent.com/assets/5026795/9536774/c956352e-4ce4-11e5-894f-608515c67122.png)

**Comment by TheoPib** [comment]
I've been playing around with this. I was able to authenticate using elinks, but I find w3m really hard to use (I could not submit my username and password via form with it).

**Comment by michael-lazar** [comment]
That's strange. For me it works, all I have to do is

1. cursor over the username box and [Enter] to type username
2. cursor over the password box and [Enter] to type password
3. cursor over the log in link and [Enter] to submit

Either way, I just picked w3m as an example. elinks is good too. As long as you can get it working in at least one terminal web-browser I'm happy

**Comment by TheoPib** [comment]
Well, maybe w3m doesn't support my terminal emulator well enough. Either way, I find elinks more user-friendly. I'll work with that.

**Comment by TheoPib** [comment]
I think the best way to handle this is to open the web browser in a new window, but I can't find a universal way to do this. Do you know if it's possible ?

**Comment by michael-lazar** [comment]
You don't always have the ability to open a new window, e.g. if you're running through SSH and don't have an x session.

**Comment by TheoPib** [comment]
Okay, then another possible way is to stop the curses session, and start it again when terminal web browser is closed.

**Comment by michael-lazar** [comment]
Have you seen https://github.com/michael-lazar/rtv/blob/master/rtv/helpers.py#L85? That's pretty much what I do there with
```
curses.endwin()
webbrowser.open_new_tab(url)
curses.doupdate()
```

*open_new_tab()* only spins off a new subprocess if the webbrowser is a BackgroundBrowser (e.g. chrome, firefox, etc.) For terminal browsers it will block until the process is closed.

**Comment by TheoPib** [comment]
I haven't seen that, thanks! I'll use this then.

**Comment by michael-lazar** [comment]
Merged, I feel a lot better knowing we can do this now. Thanks for the patience!
