### ISSUE TITLE
Support URLs in comments and selfposts

### ISSUE THREAD

**Issue by mrjovanovic** [michael-lazar/rtv#144]
Right now, URLs that are embedded in self-posts or comments are just plain text. It would be nice if one could press a button and the URLs would be listed with an option to open them in $BROWSER.

**Comment by michael-lazar** [comment]
Hi! Thanks for the suggestion, this looks very similar to https://github.com/michael-lazar/rtv/issues/100.

**Comment by mrjovanovic** [comment]
Oh, I'm sorry! I searched, but my original gripe was with self-posts, and that's probably the search term I used. I'll close this and go over there. Thanks for alerting me to the other issue!
