### ISSUE TITLE
support for multireddit

### ISSUE THREAD

**Issue by xcombelle** [michael-lazar/rtv#145]
Overall I find your tool fantastic. It only miss one feature that I need for my current use of reddit

 I usually browse /me/m/programming (or /u/xcombelle/m/programming for anyone wanting have a look on it) the main purpose is to have the number of subreddits caped to 50 so no missing any post of the more interesting subreddit.

**Comment by michael-lazar** [comment]
Sounds pretty straightforward and I think this would be a good feature to add. PRAW has a ``get_multireddit()`` method that we can use.

**Comment by xcombelle** [comment]
Actually even if it would be good, it's less urging now as it occured to me that I used reddit in a strange way, using a multireddit as a front page. Now I had change my front page to make as my favorite subreddit.

**Comment by bsteindorf** [comment]
I would also love this Feature, i use mostly multireddit's so ican sort subreddits into topics :-)

**Comment by brianluby** [comment]
I agree this would be a nice feature.  I use it often to browse topics that are related in one view.

**Comment by lynnard** [comment]
@xcombelle how did you make your multireddit 'your favorite subreddit'? I couldn't figure out a way to easily let rtv display my multireddit - in fact, I have to change its config to read in a long list of subreddits plused together on program start, and once I navigate to another subreddit I lose that page.

**Comment by xcombelle** [comment]
It was my favorite way to navigate throw the website (not via rtv that was the problem). But I eventually made it my front page

**Comment by michael-lazar** [comment]
Finally merged in https://github.com/michael-lazar/rtv/pull/233, thanks @woorst 

![image](https://cloud.githubusercontent.com/assets/5026795/17050478/ea77a74e-4fa7-11e6-8d4a-9159c9fa308a.png)
![image](https://cloud.githubusercontent.com/assets/5026795/17050541/4911ca96-4fa8-11e6-8cc8-11c0d004ecb5.png)
