### ISSUE TITLE
[Feature request] Show post count/page count

### ISSUE THREAD

**Issue by BlitzKraft** [michael-lazar/rtv#154]
As of now, there is not a way to determine how deep I have been browsing. Is it possible to show a serial number for the posts?

**Comment by yskmt** [comment]
I think post count can be displayed relatively easily, but not sure about page count, as you can scroll down post-by-post, and you can't really define "pages".

**Comment by BlitzKraft** [comment]
I agree. Just the post count would make browsing more manageable. I would just like to see how deep I have been browsing.

**Comment by michael-lazar** [comment]
:+1: Sounds like a good idea. I don't think that the serial number is explicitly returned by the api, but it would be easy enough to generate ourselves. Where do you think it would be best to display? 

Before the title
```
 1. Warner Bros.' 'Pan' Could Lead to $150 Million Loss
 http://www.hollywoodreporter.com/news/warner-bros-pan-could-lead-831412
 4352 pts • 5hr 1844 comments
 baconandpizza /r/movies News
```

or somewhere else
```
 Warner Bros.' 'Pan' Could Lead to $150 Million Loss
 http://www.hollywoodreporter.com/news/warner-bros-pan-could-lead-831412
 1 • 4352 pts • 5hr 1844 comments
 baconandpizza /r/movies News
```

**Comment by zambonin** [comment]
Before the title looks better. There are already too many numbers on the third line, it'd look cluttered in my opinion.

**Comment by michael-lazar** [comment]
Added in d52f5747463645cc5e520daf9c40d08db43c84d8.
