### ISSUE TITLE
Clear terminal title when the program exits

### ISSUE THREAD

**Issue by michael-lazar** [michael-lazar/rtv#157]
When RTV launches it overwrites the terminal's title to ``rtv 1.x.x``. However, when the program exits the title does NOT get changed back. Ideally we should edit the *finally* block inside of ``__main__.py`` to reset the title to whatever it was before we changed it.

**Comment by shaggytwodope** [comment]
What terminals are effected by this? Tested in urxvt, gnome-terminal, xterm. And it resets after exiting for me.

**Comment by michael-lazar** [comment]
You're right, it's working for me now too. Not sure what happened.
