### ISSUE TITLE
/r/me returns "Not logged in"

### ISSUE THREAD

**Issue by THS-on** [michael-lazar/rtv#160]
The logs only show normal http requests and I can see all my subs and compose comments.
Picture:
![rtv](https://cloud.githubusercontent.com/assets/10854414/10541151/0e6b32f8-740f-11e5-89ce-e28ec4da564f.png)

**Comment by michael-lazar** [comment]
Just fixed this 972fc4ad9a718a6f4f82ded00e4aad85aca82355, thanks for alerting me. I will try to get a bugfix release out in the next couple of days to address the issues that have popped up in v1.6
