### ISSUE TITLE
Display new messages prompt fails when not logged in

### ISSUE THREAD

**Issue by yskmt** [michael-lazar/rtv#163]
When I am not logged in, hitting `i` causes the following error and crashes the program:

    LoginOrScopeRequired: ``get_unread` requires a logged in session or the OAuth2 scope 
    `privatemessages`` requires a logged in session

rtv: 1.6
praw: 3.3.0

**Comment by michael-lazar** [comment]
Nice catch, my apologies for letting all of these bugs slip through to the release.
