### ISSUE TITLE
ConnectionResetError(104, 'Connection reset by peer') when opening links

### ISSUE THREAD

**Issue by boolean-is-null** [michael-lazar/rtv#168]
I've been disconnected a couple of times now, when I tried to open random links with the enter key.

The following output was printed to the CLI:
`ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

**Comment by michael-lazar** [comment]
Hi! Thanks for opening an issue. Would you mind starting with logging enabled
```
rtv --log /tmp/rtv.log
```
and paste the logfile the next time the error occurs?

**Comment by boolean-is-null** [comment]
Thank you for the quick answer..
I've attached the log file.

**Comment by michael-lazar** [comment]
Hmm...

So it looks like this is a legitimate HTTP connection reset generated by the underlying requests library. This isn't something that I have control over, besides possibly catching the exception when the connection drops and doing something sane with it. Under normal operation your connection shouldn't be reset, so I'm not sure if you're sending a bad URL or what else is going on. 

I have a few questions that might aid in helping me to reproduce this:
- How frequently does this happen?
- Is is reproducible (will opening the same submission always fail)? If so, can you give an example of a bad submission?
- Are you signed in to you reddit account when this happens?
- Is it only when you press `Enter` to open the submission, or does it also happen when you press `l` to view comments?

**Comment by boolean-is-null** [comment]
As you described my problem I suspected my VPN, which causes similar behavior in other programs.

The error was not reproducible at all without my VPN connection, so it doesn't have to do with `rtv`.
