### ISSUE TITLE
[feature request] Subreddit sorting menu

### ISSUE THREAD

**Issue by wedens** [michael-lazar/rtv#171]
Changing sorting order using `/<retype subreddit name>/new` is not very convenient. It'd be nice to have a menu to select hot/new/top/ sorting. and perhaps another menu for `front` with hot/new/rising/top/controversial

**Comment by michael-lazar** [comment]
You can actually already do this on subreddits and submissions by using the 1-5 number keys, see https://github.com/michael-lazar/rtv#basic-commands. I do think it would be cool to have a graphical banner at the top of the screen with something like

```
[1]hot [2]top [3]rising [4]new [5]controversial
```
so it would be a bit more obvious

**Comment by wedens** [comment]
@michael-lazar nice! thanks. yeah. making it more obvious  is a good idea

**Comment by michael-lazar** [comment]
I've implemented this and merged it in here 52dfbe786c70d15c30b2561ea63d2c4190b16b5c. The menu is at the top of the screen and the selected order is highlighted (``top`` in this example).

![screenshot from 2015-12-09 00 29 40](https://cloud.githubusercontent.com/assets/5026795/11680297/fe283342-9e0b-11e5-920d-5469237e8a44.png)

If people like/dislike this or have any suggestions, please let me know.

**Comment by wedens** [comment]
@michael-lazar thanks for adding this! 
is this menu also present for subreddits?

**Comment by michael-lazar** [comment]
Yes! The menu is the same for both subreddits and submissions

![image](https://cloud.githubusercontent.com/assets/5026795/11703778/c315b5d2-9e96-11e5-8545-8b91e6945d9b.png)
![image](https://cloud.githubusercontent.com/assets/5026795/11703792/d3114064-9e96-11e5-9bea-5ae1e243cf58.png)

**Comment by yskmt** [comment]
looks cool

**Comment by michael-lazar** [comment]
Thanks yskmt :wink:. I'm closing the issue for now, if anybody has any further suggestions feel free to re-open.

**Comment by kalentia** [comment]
Is there any way to choose a time constraint for sorting, e.g. day, week, month, etc.?

**Comment by michael-lazar** [comment]
@kalentia You can if you type it in the prompt like

```
/r/python/top-all
/r/python/top-week
```

There is no way to select it though the gui yet though.
