### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by g33kdad** [michael-lazar/rtv#172]
Every time i try to launch rtv, i get an ssl error "SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)".

I am on openSUSE "Tumbleweed", I have both Python 2.7.10 and Python 3.4.3 installed on my system, i installed rtv with 'sudo pip3 install -U rtv' per the readme file, running under i3-wm.

I have tried uninstalling and reinstalling...

Thoughts?

**Comment by michael-lazar** [comment]
Hi, thanks for reporting the issue. This may be out of rtv's domain, everything in the SSL realm is handled by the underlying python libraries. Other people on openSUSE have also reported problems (See https://github.com/michael-lazar/rtv/issues/152). From what I understand, the issue might be that you  have invalid SSL certs, or your SSL certs are in a non-standard location that python isn't finding.

**Comment by michael-lazar** [comment]
A fix for this was merged into requests a while ago https://github.com/kennethreitz/requests/issues/2659. I can't test because I don't run openSUSE, but I'm going to assume that this issue is resolved now.

**Comment by g33kdad** [comment]
Thanks for keeping me in the loop. I'm not running opensuse anymore so....
Anyway, good luck.
