### ISSUE TITLE
[feature request] open subreddit, history and caching

### ISSUE THREAD

**Issue by Glumanda99** [michael-lazar/rtv#175]
You can open the url on a post (i guess it is called submission in prav) wih `o`, the thread itself with `l`, but not the subreddit itself. I would like to open with `L` (uppercase).

**Comment by michael-lazar** [comment]
Hi, thanks for the suggestion. This would only effect cross-posts, correct? Could you give a specific example?

**Comment by mnlgn** [comment]
I was looking at the rtv front page and multi reddits, so I can dig into the subreddit from there. I also tend to use `h` to go back any further as i thought it would work more like the back button in a browser. Sadly, this is not the case with rtv: i would have to enter my subscribed subreddits again with `s`. I wish to see some caching going on for faster browsing and moving around.

Pls make this happen, Santa! :santa:

**Comment by michael-lazar** [comment]
:+1: on going back to the subscriptions with ``h``.

The caching is an interesting point. PRAW already has a built-in request cache that defaults to 30 seconds https://github.com/praw-dev/praw/blob/master/praw/praw.ini#L13. So it should already be kicking into effect most of the time. There are actually some times when this gets in the way (e.g. after you post a comment and want to request the newest copy of the page.)

I'll think about the ``L`` usage. I see where you're coming from, and it would be easy to implement. I just try to be careful before adding new keystrokes, and make sure that they're intuitive and there's a real need.

**Comment by mnlgn** [comment]
You-re right. I guess I came up with the caching issue as I'm going back a lot to my subreddits list and it is downloading each time (after 30 secs). This is where I felt slow with rtv. I'm kinda new to reddit but checking all my subreddits frequently I feel more comfortable with than the mix on the front page where I get lost pretty fast.

Thank you for looking into it and sorry for all the work! Kiss ya cheek :kissing_cat:

**Comment by michael-lazar** [comment]
I'm clearing out old issues. The ``L`` feature hasn't been requested by anyone else in the last two years so I don't think it's worth adding a key binding at this point. Discussions on page caching can be continued in #177
