### ISSUE TITLE
[Feature request] Support for saving posts/comments, viewing saved posts/comments

### ISSUE THREAD

**Issue by daturkel** [michael-lazar/rtv#180]
Reddit supports saving posts to a single list tied to the user, for instance, [my saved posts](https://reddit.com/user/daturkel/saved). It would be nice if RTV allowed for the saving of posts (shortcut from sub view or from post comment view) and a way to view those saved items in a list (like the /user/[username]/saved page on reddit).

Potential obstacle: Reddit allows for the saving of both posts and comments.
a) Since comments are saveable, it might be necessary for two separate shortcuts in the comment view—one to save the highlighted comment and one to save the entire post.
b) Viewing the list of saved items might need to be formatted in a way that's slightly different from a typical subreddit view since it can include both posts and comments.

**Comment by michael-lazar** [comment]
Thanks for bringing this up, I agree that it would be a nice feature to add.

PRAW has a function **r.user.get_saved()** that we could use to retrieve the user's saved items.

On point A, I think that we can use the same logic as when you press "o" in the *comment view*. If no comment is selected i.e. the submission is selected, you save the submission. If a comment is selected, you save the comment. In both cases we would need to add a flair, like the NSFW flair, to indicate that the item has been saved.

On point B, I think the most straightforward thing would be to add support for comments to the *subreddit view* and put in a new alias (e.g. **/r/saved**) similar to how **/r/me** works to view your submissions.

**Comment by daturkel** [comment]
Agreed with both of your solutions! Looking forward to seeing this somewhere down the line.

**Comment by alexk307** [comment]
I've got point B, working on Point A!

**Comment by alexk307** [comment]
@michael-lazar which key would be the best to bind to this saving functionality?

**Comment by alexk307** [comment]
I've also left a few questions in the PR about how to handle a few specifics. Thanks!

**Comment by michael-lazar** [comment]
Hi Alex! You should sync up with @tyjak, he made a pull request for the same issue a few days ago https://github.com/michael-lazar/rtv/pull/187. Maybe you guys can pool your PR's together and come up with the best solution? To answer your questions:

- I like tyjak's keybinding of <kbd>w</kbd>. I have no strong inclination either way, but I like w because it's easy to type and it's close to the other modifier keys (upvote, downvote, edit, delete, etc.)
- The "saved" label should be applied immediately. The trouble is that reddit caches pages every 30ish seconds of so. If you wait for reddit to acknowledge your saved post, it might not show up for a while even if you refresh the page. Check out how I implemented upvote/downvote for reference.

**Comment by michael-lazar** [comment]
For viewing saved comments, I think if you start with something like this you'll be on the right track.

**content.py**
```python
class SubredditContent(Content):
    ...
    def get(self, index, n_cols=70):
        ...
        if isinstance(submission, praw.objects.Comment):
            # Special case for mixed views e.g. saved comments/submissions
            data = self.strip_praw_comment(submission)
        else:
            data = self.strip_praw_submission(submission)
```

**subreddit.py**
```python
class SubredditPage(page):
    ...
    def _draw_item(self, win, data):
        if data['type'] == 'Comment':
            # This method still needs to be implemented
            # The format will be slightly different than the one used to
            # draw comments inside of the SubmissionPage
            return self._draw_comment(win, data)
        else:
            return self._draw_submission(win, data)

**Comment by alexk307** [comment]
Ahhh I should've seen that there was another PR open for the same thing. @tyjak Let me know if I can help out in any way or if there's any part you don't want to do.

**Comment by tyjak** [comment]
Hi Michael, Hi Alex, thank you @alexk307 to have done the part I had not done yet :) I merged your version in my PR. I keep 3 things of mine : centralized save action, green [saved] similar to green [stickied] and 'w'  key to save. I still need to add test code. @alexk307 I let you improve anything you seem that need to. @michael-lazar is this good for you ?

**Comment by tyjak** [comment]
I just figured out the comments view in saved list needs to be done. Alex have you time to do that part ?

**Comment by alexk307** [comment]
Awesome, thanks! I'll take a look. Yes I can do the comments in the saved list. I'll also try to write some tests soon.

**Comment by alexk307** [comment]
@tyjak I opened a PR into your branch to do the last part.

@michael-lazar instead of adding a whole other function to parse the comments into submissions, I ended up editing the `strip_praw_submission` function to be more flexible. It will now detect if a comment was passed in and will parse it into a submission. Let me know what you think!

**Comment by alexk307** [comment]
The only thing I noticed is that it takes more time than usual to load all of the saved posts when the comments are added in. I'll investigate some more later.

**Comment by michael-lazar** [comment]
@tyjak yeah that sounds great!

@alexk307 I would suggest that you run with logging enabled (``rtv --log /tmp/rtv.log``) and watch the requests that are being made. My guess is that one of the comment attributes that you're trying to access is triggering praw to make a separate http request.

**Comment by michael-lazar** [comment]
This was merged in https://github.com/michael-lazar/rtv/pull/187
