### ISSUE TITLE
Add a · (center dot) between timestamp and comment count in subreddit view

### ISSUE THREAD

**Issue by daturkel** [michael-lazar/rtv#183]
There's a · symbol between the points and timestamp that changes to a triangle if you up/downvote. It'd be nice if there was also a · between the timestamp and the comment count, just for a little visual consistency and separation. It probably wouldn't ever have to change to anything.

**Comment by 5225225** [comment]
![2016-01-08-101150_1920x1080_scrot](https://cloud.githubusercontent.com/assets/8584210/12195645/95b8e264-b5f0-11e5-8ef3-c850c0a34949.png)

This is what it looks like on my machine. I think it looks alright for things that haven't been voted on, but looks a bit asymmetric when only the left one changes when you vote.

**Comment by daturkel** [comment]
Hmm, I guess this will always depend on the font in use. It will surely be symmetrical when the story is voted on, but depending on the triangle shapes in the font, it will look different. My triangles are a lot bigger than yours:
![http://i.imgur.com/4JuqSqe.png](http://i.imgur.com/4JuqSqe.png)

**Comment by michael-lazar** [comment]
I think that if they were static bullets then it would look good having them both there. However, 5225225 raises a good point about the asymmetry. The first bullet represents a "neutral" vote while the second bullet is just a separator. I don't like that there is nothing to visually distinguish between the two bullets.

**Comment by zambonin** [comment]
Instead of using `U+2022` (•), perhaps `U+25E6` could be used (◦) for the separator. Or even `U+2023` for the neutral vote (‣), to match the other triangles.

**Comment by 5225225** [comment]
Yeah, 2023 looks fine for a neutral vote. Also works in ASCII as >.

I'll write that and see how good it looks.
