### ISSUE TITLE
[Feature request] Don't display sticky posts the same as regular posts

### ISSUE THREAD

**Issue by gislifreyr** [michael-lazar/rtv#184]
It would be great if sticky posts would be displayed differently from regular posts when the page is sorted by "hot".

So implementing one/both of these features:
* Stickied posts are in another colour
* Stickied posts are not numbered. Numbering starts on first "regular" post.

Don't know if praw supports checking if posts are stickied but if it does this might not be a hard problem to solve. I might even try to solve it myself.

**Comment by michael-lazar** [comment]
Good idea! I'm pretty sure the reddit api supports this e.g.
```
submission.stickied
```
I would vote for either using a different color or adding a ``[stickied]`` tag to the posts. Feel free to make a PR if you would like.
