### ISSUE TITLE
Links are not opened properly

### ISSUE THREAD

**Issue by jrlil** [michael-lazar/rtv#189]
Whenever I attempt to open links in parenthesis in web browser, the last bracket is included in the url, so the links appear broken. Fot instance, if I click on the url part of linked text "(www.link.com)", it is opened as "www.link.com)". I use rtv in Termite terminal and open links in Firefox browser.

**Comment by michael-lazar** [comment]
Hi jrlil. Are you using the keyboard (<kbd>o</kbd> or <kbd>Enter</kbd>), or your mouse to click on the links? If it's your mouse, that behavior is defined by your terminal and not rtv.

**Comment by jrlil** [comment]
I was talking about links inside comments that cannot be opened with keyboard. But you're probably right, it's a terminal issue. Thanks!
