### ISSUE TITLE
[Feature request]: Key binding for jumping to "my subreddits" in one keystroke

### ISSUE THREAD

**Issue by matthiasbeyer** [michael-lazar/rtv#190]
When logged in, I don't know how to jumb back to my frontpage. I guess going to `/r/front` would be enough, though I'd like to see a keybinding for this.

**Comment by zambonin** [comment]
That's not a bad suggestion at all. Maybe the `h` letter could be used for "home"?

**Comment by matthiasbeyer** [comment]
I'd vote for not breaking the current mappings, so I'd say that the binding should go to a key which is not bound yet.

Either way, I'd vote against `h`, as currently `h` works like `hjkl` in vi-like editors, which is a really nice feature IMHO. `x` sounds nice for me...

**Comment by mardiqwop** [comment]
Once I started using this, I had the exact same wish. I went ahead and added a keybind for that on my fork.

**Comment by matthiasbeyer** [comment]
@mardiqwop did you file a PR?

**Comment by mardiqwop** [comment]
@matthiasbeyer yes. I'm still learning git, though. I'm not sure I did it correctly, but my pull request is showing up.

**Comment by michael-lazar** [comment]
Link to the PR https://github.com/michael-lazar/rtv/pull/241 mentioned above

**Comment by michael-lazar** [comment]
The PR mentioned above is now merged in. We went with the <kbd>p</kbd> key for this.
