### ISSUE TITLE
[Feature request / UI]: Show whether thread was up/down voted by me

### ISSUE THREAD

**Issue by matthiasbeyer** [michael-lazar/rtv#191]
There is no indicator whether a thread was up- or downvotes by me, is there?

**Comment by zambonin** [comment]
Between the karma score of the thread and when it was posted, there should be an arrow indicating whether your vote was positive or negative, and if it exists at all.

You can see a picture of that on the README.

If you're sure your `rtv` instance does not show that, then perhaps it could be a bug.

**Comment by matthiasbeyer** [comment]
No, there is no such arrow.

**Comment by michael-lazar** [comment]
Hi Matthias, could it be that you're using a terminal that doesn't support the arrow unicode chars? 

Would you mind positing two screenshots of your environment, one using ``rtv`` normally and one using ``rtv --ascii`` to force ascii-only mode?

**Comment by matthiasbeyer** [comment]
Uh, there is a `ascii` mode! Nice! I will provide screenshots asap.

I'm using xterm and rtv is running inside a tmux.

**Comment by michael-lazar** [comment]
Marking as closed, please re-open if you have more info!
