### ISSUE TITLE
Respect http_proxy and https_proxy

### ISSUE THREAD

**Issue by triggerNZ** [michael-lazar/rtv#198]
When connecting through a proxy, `rtv` fails to connect. The usual convention is for internet-connecting programs to read the `http_proxy` and `https_proxy` environment variables.

**Comment by michael-lazar** [comment]
Might be a different issue, proxies are supposedly handled behind the scenes by praw. Environment variables should already work.

https://github.com/praw-dev/praw/blob/master/praw/__init__.py#L258

**Comment by triggerNZ** [comment]
Interesting... Closing this until I have more detail.
