### ISSUE TITLE
[Feature Request] shortcut to open urls in different softwares

### ISSUE THREAD

**Issue by marteaurouge** [michael-lazar/rtv#202]
Ranger is doing that, if you hit r, you can choose another command to open the selected url.

An example would be to open Youtube urls directly with vlc or mpv.

A config file to set custom openings would be interesting like:

youtube.com mpv #all youtube urls would be opened with mpv
imgur.com chromium
theverge.com lynx

**Comment by michael-lazar** [comment]
See https://github.com/michael-lazar/rtv/issues/78. I also really want this but it's been tough to come up with the best way to implement and test this without breaking functionality for some people.

Obsob has the best workaround for now, you can set $BROWSER to point to a bash script that does whatever custom rules you would like

```BROWSER=urlscript rtv```

and in urlscript:

```bash
#!/bin/bash
case $1 in
    http*://*youtube.com/watch?*|http*://youtu.be/watch?*)
         mpv "ytdl://$1"
    ;;
    *.gif|*.gifv)
         mpv "$1"
    ;;
    *.jpg*|*.png*)
        feh -. "$1"
    ;;
esac 
```
