### ISSUE TITLE
[Feature Request] local subreddit list when not logged

### ISSUE THREAD

**Issue by marteaurouge** [michael-lazar/rtv#203]
When hitting s , a subreddit list is popping, but not if you're not logged.

What about a config file to store locally a list of your fav subreddit, so the s feature would be useful even without using an account.

**Comment by spcmd** [comment]
Yes, It would be great to have them stored locally in a plain text file. I think it would be faster to open the list too.

**Comment by michael-lazar** [comment]
Cleaning out duplicate issues, discussion can continue on #322
