### ISSUE TITLE
Can't read long text posts

### ISSUE THREAD

**Issue by tschuy** [michael-lazar/rtv#205]
When reading long text posts, I get

> (Not enough space to display) 

and have to zoom out to read it all, which is super annoying. I've tried j/k, n/m, the arrow keys, all of them skip to the first comment.

There should be a way to "scroll" through the post without skipping to comments.

**Comment by michael-lazar** [comment]
See https://github.com/michael-lazar/rtv/issues/93. This was recently merged into master but hasn't been released to pypi yet so you can't pip install it.

**Comment by tschuy** [comment]
Ah perfect! I'll give it a go next time I'm redditing :)

**Comment by avh-on1** [comment]
Is there any timeline for getting this into pip?
