### ISSUE TITLE
[feature request] Add support for console-based mouse and buttons

### ISSUE THREAD

**Issue by rcampbel3** [michael-lazar/rtv#220]
It would be nice if rtv could support mouse input as well.

Perhaps using this?
https://github.com/SavinaRoja/PyUserInput

**Comment by michael-lazar** [comment]
Python's curses module already has the ability to register mouse clicks ([see here](https://docs.python.org/2/library/curses.html#curses.getmouse)) so we wouldn't even need to use a third-party library.

**Comment by michael-lazar** [comment]
I'm cleaning out old issues and nobody has expressed interest in this. Feel free to re-open if you would like to continue the discussion.

**Comment by bkuri** [comment]
I'd like a way to reverse mouse wheel scrolling behavior. Currently scrolling the mouse down scrolls up and viceversa.
