### ISSUE TITLE
Window title not set

### ISSUE THREAD

**Issue by a-roy** [michael-lazar/rtv#221]
I just installed RTV on Arch Linux using the rtv package from the AUR. When I run RTV, it does not change the title of my terminal window. If I run code such as `sys.stdout.write('\x1b]2;TITLE\x07')` in my terminal, however, it works as expected.

**Comment by BlitzKraft** [comment]
What's the terminal you are using?

**Comment by a-roy** [comment]
I'm using termite. I tried xterm and still got the same issue.

**Comment by michael-lazar** [comment]
Hi a-roy, thanks for the bug report.

What version of python are you using? I wonder if it might be a unicode problem. Try saving this as a script and running it. 

```python
# -*- coding: utf-8 -*-
import locale
import sys
from __future__ import unicode_literals

locale.setlocale(locale.LC_ALL, '')
title = 'TEST'
sys.stdout.write('\x1b]2;{0}\x07'.format(title))
```

**Comment by a-roy** [comment]
I'm using Python 3.5.1. The above code works for me for both Python 3.5.1 and 2.7.11.

**Comment by a-roy** [comment]
I just discovered that rtv is actually setting the window title after I quit. I hadn't noticed it before due to my shell immediately changing it again.

**Comment by michael-lazar** [comment]
Just saw your edit, thanks!

**Comment by michael-lazar** [comment]
Fixed
