### ISSUE TITLE
Open Inbox

### ISSUE THREAD

**Issue by ro0kie4** [michael-lazar/rtv#232]
Hello,

When I press "I" to open my Inbox I get a prompt that says "new Messages" but I can't open them. Hope can I see my messages?

Thanks 

ro0kie4

**Comment by llvtt** [comment]
This feature isn't available yet, but I'm actively working on it. There's a discussion about the feature in #109. Hopefully I'll have a pull request up with at least basic functionality by the end of next weekend.

**Comment by michael-lazar** [comment]
Closing as duplicate issue
