### ISSUE TITLE
"^@" in comments

### ISSUE THREAD

**Issue by jonnagel** [michael-lazar/rtv#235]
Any ideas about what is causing [this](http://imgur.com/3cuLUjx)? It's only in the comments. Same thing with different terminals and fonts.

**Comment by michael-lazar** [comment]
Thanks for reporting this. 

It looks like curses is trying to print a vertical bar ([*ACS_VLINE*](http://melvilletheatre.com/articles/ncurses-extended-characters/index.html)) to the terminal, but failing and sending a [NUL](http://vimdoc.sourceforge.net/htmldoc/digraph.html#digraph-table) character (0x00) instead. Normally, if the terminal doesn't support the vline character, curses should automatically detect it and fall back to using a PIPE ( **|** ).

What OS / terminal / python version are you running? Also, does the box at the top of the comments page look like that too? Here's what it looks like for me for reference.

![terminal_050](https://cloud.githubusercontent.com/assets/5026795/16399776/74a32ab4-3c8a-11e6-8e94-38090ffa8e4f.png)

**Comment by jonnagel** [comment]
Thanks for the reply.

[Comments page with top](http://imgur.com/dBHnpMY)

Ubuntu 15.10, screen-256color-s, Python 3.5.1
Same with or without tmuximg

**Comment by michael-lazar** [comment]
I added a section to the FAQ but have been unable to reproduce this, feel free to reopen if you have any additional info.
