### ISSUE TITLE
Top Hour/Day/Week/Month/Year

### ISSUE THREAD

**Issue by demipixel** [michael-lazar/rtv#244]
At the moment, only "top" is available. I presume that's "top today"?

**Comment by michael-lazar** [comment]
Yea that's correct, the default is to view the last 24 hours. Thanks for commenting, a couple of people have brought up this issue already. I agree that it would be nice to have more control over the time range, but it's not very high on my priority list.

Here's an (abandoned?) pull request https://github.com/michael-lazar/rtv/pull/226 that I think was on the right track.

**Comment by michael-lazar** [comment]
Ok now you can specify the period by typing 
```
/r/front/top-year
```
However, there's still no way to pick the period using the toolbar at the top, and there's no visual feedback.

**Comment by michael-lazar** [comment]
This is a duplicate of #308 so I'm going to close it and redirect discussion to the newer issue.
