### ISSUE TITLE
Loading more comments is slow

### ISSUE THREAD

**Issue by michael-lazar** [michael-lazar/rtv#25]
Trying to load a large block of additional comments e.g. `│More comments [427]` takes a very very long time and a large number of http requests. I remember looking into this a while ago and finding out it was a limitation in the Reddit API itself. Never the less, we should try to find out if PRAW has an alternative method to the `praw.objects.MoreComments().comments()` which is currently being used.

**Comment by tobywhughes** [comment]
What about loading the next comments in the background?

**Comment by mekhami** [comment]
yeah, prefetching!

**Comment by tobywhughes** [comment]
^I just learned a word.

**Comment by michael-lazar** [comment]
Referenced at https://github.com/praw-dev/praw/issues/391

**Comment by michael-lazar** [comment]
Fixed d051e5e. Implementation is sort of a hack right now to work around praw. Hopefully there will be an opportunity to clean this up when praw gets updated.
