### ISSUE TITLE
Can't launch rtv when front page contains no submissions

### ISSUE THREAD

**Issue by woorst** [michael-lazar/rtv#251]
If you have an empty front page, i.e. you are not subscribed to any subreddits, rtv will exit immediately after launch.

**Comment by woorst** [comment]
Nevermind, the subreddit launched on initialization can be configured in `rtv.cfg`.

**Comment by michael-lazar** [comment]
Thanks for posting. I'm going to re-open this because I think it's an edge case that we should at least handle gracefully.
