### ISSUE TITLE
[Feature request] Sort by time period

### ISSUE THREAD

**Issue by edridgedsouza** [michael-lazar/rtv#252]
Could you add an option so that within the "sort" categories, you can specify a time period? When I sort posts by "top", the default seems to be by "week". I tried changing this by pushing `/` and entering `subreddit/top/?sort=top&t=month`, as I would in the browser. However, the script doesn't support that many slashes in the subreddit entry field.

**Comment by michael-lazar** [comment]
I think this is the same thing that was asked here https://github.com/michael-lazar/rtv/issues/244, so I'm marking as duplicate.
