### ISSUE TITLE
[Feature request] Expand and collapse

### ISSUE THREAD

**Issue by edridgedsouza** [michael-lazar/rtv#253]
It would be useful to collapse comment threads (or to have a function to skip to the next comment in the same level of the hierarchy). 

Also, there should be an option for expanding when it says `│More comments [12]`

**Comment by michael-lazar** [comment]
Try pressing the <kbd>space</kbd> key ;-)

**Comment by edridgedsouza** [comment]
Aah, thanks! Sorry, I'd been trying to use `rightarrow` or `l` to do it.
