### ISSUE TITLE
Displaying comments that don't fit on the screen

### ISSUE THREAD

**Issue by michael-lazar** [michael-lazar/rtv#26]
Single comments that are too large to fit in the screen will only be partially displayed. There is currently no way to view the hidden part of the comment, as scrolling down jumps all the way to the beginning of the next comment. Suggestions on how to solve this problem are welcome.

**Comment by tobywhughes** [comment]
There could be a secondary key bind that allows the user to scroll through the post manually. The amount of scroll increases as they go down the post and resets if another post is reached.

Or we could have to completely separate key binds. One for scrolling post by post and the other for scrolling down line by line.

**Comment by michael-lazar** [comment]
I like the second idea. Would be tricky to implement though, based on how I wrote the page scrolling.

**Comment by tkajder** [comment]
I tinkered around with the code and got very basic scrolling using 'y' and 'u' as scroll up and down. Curses made this pretty basic:

```python
# Setting scrolling support
self._content_window.scrollok(True)

# Scrolling the content
self._content_window.scroll(1)
self._content_window.refresh()
```

However since the content is only drawn to what is visible on the screen scrolling does not do much as of yet. I'll try tinkering with the drawing method when I get time.

**Comment by Brobin** [comment]
In addition, posts that don't fit on the screen aren't displayed at all. For example, when nagivating to [this post](http://www.reddit.com/r/ProgrammerHumor/comments/30tio4/call_for_discussion/), we simply see `(Not enough space to display)`, no comments or anything. I think it should show at least some of the content and the comments.

**Comment by michael-lazar** [comment]
@Brobin Fixed in ca41b77

**Comment by michael-lazar** [comment]
Closing this because it would require a major rewrite of how screen paging is currently implemented. If anybody has additional input or ideas about this, feel free to open a new issue.

**Comment by pelegm** [comment]
Perhaps an option to open a post in vim? (read-only mode)

**Comment by michael-lazar** [comment]
Actually this feature was added here https://github.com/michael-lazar/rtv/issues/93. It uses ``less`` instead of ``vim`` though.
