### ISSUE TITLE
Cannot follow links with shortened URLs

### ISSUE THREAD

**Issue by edridgedsouza** [michael-lazar/rtv#267]
Hi,

I noticed that if you run `rtv -l https://redd.it/4vqkeb` it throws `NotFound`. I'm wondering if there's a way to pre-process any URL arguments to see whether they redirect to any valid reddit.com URLs and only then load it into RTV; this would take care of not only redd.it domains but also bit.ly and other URL shorteners.

As a side note: is there a shortcut once you're within RTV to navigate to a specific page? I'll often come across a link to another reddit page somewhere in a comments section, copy the link, exit rtv, and run `rtv -l pastedurl`. I might just be unaware of whether this feature exists, so never mind this if it does.

**Comment by edridgedsouza** [comment]
I looked into it a bit. You can use `os.system()` to execute some of the functions here: https://www.commandlinefu.com/commands/view/9515/expand-shortened-urls

However, when I try `expandurl() { curl -sIL $1 | grep ^Location; }` on `redd.it/blahblah`, it outputs `reddit.com/tb/blahblah`, which also doesn't work. When I try to use `expandurl()` again on this result, it gives me a blank. Can anyone think of a way around this?

**Comment by michael-lazar** [comment]
Hey thanks for pointing this out. Currently we pass the url straight through to PRAW like this

```python
import praw

r = praw.Reddit('rtv #267')
r.get_submission(url='https://redd.it/4vqkeb')
```
I kinda would have expected them to be able to handle this, it might be worth bringing up on their [issue tracker](https://github.com/praw-dev/praw/issues). If that doesn't work, you can write your own url expander with a few lines of python.

http://stackoverflow.com/a/28918160
```python
>>> import requests
>>> session = requests.Session()
>>> resp = session.head('https://redd.it/4vqkeb', allow_redirects=True)
>>> resp.url
'https://www.reddit.com/r/ProgrammerHumor/comments/4vqkeb/looks_like_someone_at_atlassian_forgot_to_remove/'
```

**Comment by michael-lazar** [comment]
And you're correct that there is currently no way to enter a link from inside of the program. It would be a nice feature to have though.

**Comment by edridgedsouza** [comment]
Yeah. I added an (unsuccessfully built) pull request into subreddit.py under the method `open_submission`:

<pre>
from urllib.request import urlopen # At beginning of doc

        try:
            redditpage = urlopen(url)
            if redditpage.getcode() == 200:
                url = redditpage.url
        except urllib.error.HTTPError:
            break
</pre>

I suppose using `requests` instead of `urllib.request` will get the same thing done. This code chunk might also be better suited if placed at line 300 of content.py, under the method `from_url` (sorry, I'm not very familiar with the structure/architecture of this code). I think somewhere in there, you can also use a regex (or PRAW?) to test whether the original command-line argument is a valid Reddit URL to prevent having to load the page an extra time.
