### ISSUE TITLE
Bindings for pageup and pagedown

### ISSUE THREAD

**Issue by michael-lazar** [michael-lazar/rtv#27]
I would like to add support for scrolling up and down a full page at a time.

**Comment by tobywhughes** [comment]
What about going from parent comment to parent comment? I feel like a full page is sort of arbitrary in terms of reddit comments. However, it would be more useful to be able to jump from the highest level parent comment to the next when going through posts like comments on askreddit where a single parent post can have hundreds and hundreds of replies.

**Comment by michael-lazar** [comment]
Normally when I'm browsing Reddit I will fold the comment threads once I'm done with them. That's at least one way to jump to the next parent comment. I assume that's what reddit expects you to do, at least I haven't found anything to tell me otherwise. I'm going to start working on this. I'll try out both ways and see what feels more natural.

**Comment by michael-lazar** [comment]
Implemented by the awesome @yskmt. Key bindings are `n` for pageup and `m` for pagedown. I'll update the README before the next release goes out.
