### ISSUE TITLE
rtv 1.11.0 exits on start

### ISSUE THREAD

**Issue by arvedarved** [michael-lazar/rtv#277]
Just after start, the start screen is shown for some milliseconds, then the following backtrace appears:

Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 9, in <module>
    load_entry_point('rtv==1.11.0', 'console_scripts', 'rtv')()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.4/site-packages/rtv/__main__.py", line 157, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/rtv/__main__.py", line 138, in main
    page.loop()
  File "/usr/local/lib/python3.4/site-packages/rtv/page.py", line 70, in loop
    self.draw()
  File "/usr/local/lib/python3.4/site-packages/rtv/page.py", line 285, in draw
    self._draw_content()
  File "/usr/local/lib/python3.4/site-packages/rtv/page.py", line 386, in _draw_content
    attr = self._draw_item(subwindow, data, subwin_inverted)
  File "/usr/local/lib/python3.4/site-packages/rtv/subreddit.py", line 222, in _draw_item
    self.term.add_line(win, text, row, 1, curses.A_BOLD)
  File "/usr/local/lib/python3.4/site-packages/rtv/terminal.py", line 273, in add_line
    window.addstr(row, col, text, *params)
_curses.error: addstr() returned ERR

Not sure what other

**Comment by arvedarved** [comment]
output from testsuite if it helps:
<pre>
======================================================= FAILURES =======================================================
______________________________________________ test_open_link_subprocess _______________________________________________

terminal = <rtv.terminal.Terminal object at 0x2a1e63ac>

    def test_open_link_subprocess(terminal):
    
        url = 'http://www.test.com'
    
        with mock.patch('time.sleep'),                            \
                mock.patch('os.system'),                          \
                mock.patch('six.moves.input') as six_input,       \
                mock.patch.object(terminal, 'get_mailcap_entry'):
    
            six_input.return_values = 'y'
    
            def reset_mock():
                six_input.reset_mock()
                os.system.reset_mock()
                terminal.stdscr.subwin.addstr.reset_mock()
    
            def get_error():
                # Check if an error message was printed to the terminal
                status = 'Program exited with status'.encode('utf-8')
                return any(status in args[0][2] for args in
                           terminal.stdscr.subwin.addstr.call_args_list)
    
            # Non-blocking success
            reset_mock()
            entry = ('echo ""', 'echo %s')
            terminal.get_mailcap_entry.return_value = entry
            terminal.open_link(url)
            assert not six_input.called
            assert not get_error()
    
            # Non-blocking failure
            reset_mock()
            entry = ('fake .', 'fake %s')
            terminal.get_mailcap_entry.return_value = entry
            terminal.open_link(url)
            assert not six_input.called
>           assert get_error()
E           assert <function test_open_link_subprocess.<locals>.get_error at 0x2a054974>()

tests/test_terminal.py:421: AssertionError
</pre>

**Comment by arvedarved** [comment]
Okay, this is also caused by having LANG not set. With LANG set to a UTF-8 locale rtv works as expected.

At least a more helpful errormessage is desirable

**Comment by michael-lazar** [comment]
Hi thanks for the bug report. The python docs on [locale](https://docs.python.org/2/library/locale.html) say that 

```python
import locale
locale.setlocale(locale.LC_ALL, '')
```

sets the locale to the user's default setting (or ``LANG`` if specified). I guess that I've been taking for granted that everyone's default encoding is UTF-8. Do you mind if I ask what your default is so I can reproduce this?

```python
>>> import locale
>>> locale.getdefaultlocale()
('en_US', 'UTF-8')
```

**Comment by irmas** [comment]
I have the same error and my locale setting is 
`$ locale :`

`LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
`

(I got the package from the Arch AUR)

**Comment by arvedarved** [comment]
My default locale was unset 
<pre>LANG=
LC_CTYPE="C"
LC_COLLATE="C"
LC_TIME="C"
LC_NUMERIC="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_ALL=
</pre>

Of course without UTF-8 rtv is not very useful :-).  But this was my test box, which i use to test package builds, so it did not have any modifications.

@irmas It UTF-8 working for your other applications? Maybe your locales are not installed properly?

**Comment by michael-lazar** [comment]
I added a new check for the locale at startup. If it's not set, or if it's not utf-8, rtv will log a warning and fallback to ``--ascii`` mode.
