### ISSUE TITLE
Support for flairs

### ISSUE THREAD

**Issue by michael-lazar** [michael-lazar/rtv#28]
Would be nice if we could support flairs from different subreddits. Would look something like

![screenshot from 2015-03-05 20 20 33](https://cloud.githubusercontent.com/assets/5026795/6520183/5b4e240e-c375-11e4-859f-33c1e61aec75.png)

**Comment by tobywhughes** [comment]
Fount this in PRAW's code overview. May be helpful:

     get_flair(subreddit, redditor) 
         Return the flair for a user on the given subreddit.

         Requires the modflair oauth scope or user/password authentication as a mod of the subreddit.

         Parameters:
        •subreddit – Can be either a Subreddit object or the name of a subreddit.
        •redditor – Can be either a Redditor object or the name of a redditor.

         Returns:
         None if the user doesn’t exist, otherwise a dictionary containing the keys flair_css_class, flair_text, and user.

**Comment by shanhind** [comment]
I`m going to take a look at doing this.

**Comment by shanhind** [comment]
Hey @michael-lazar, I've been looking at doing this but I'm having trouble finding where the comments and submission text are actually set / drawn to the screen.  In the submissions.py module there are functions such as draw_submission and draw_comment.  In these there are variables called text which seem to then be put into the curses screen.  I've tried adding extra text to these text variables just to see what that would affect and it actually did nothing.  Am I misunderstanding what this section of the code does?

**Comment by michael-lazar** [comment]
That sounds like you're doing it correctly. Keep in mind that **subreddit.py** controls the main page, and **submission.py** controls the comments page. If you're trying to change the behavior of the main page, you need to look at **subreddit.draw_item()**. That being said, changing the text to something like
```python
text = '{author} test_flair'.format(**data)
```
should produce a visible output. If it still doesn't, my guess is that python is grabbing files from a different location than you are expecting. If so let me know and we can walk through setting everything up.

**Comment by shanhind** [comment]
Yeah I think Python must be grabbing files from a different place.  Should I perhaps uninstall the system wide rtv that I installed via package manager? Or what would you suggest doing?

**Comment by michael-lazar** [comment]
Here's what I've been doing lately. First make sure that your repo is up-to-date.

1. ``cd`` into the top directory (the one with ``setup.py`` and ``README.rst``)
2. type ``python -m rtv``

Explanation:
The ``-m rtv`` is shorthand for typing out ``python rtv/__main__.py``. When python sees the lines

```python
from rtv.main import main
main()
```

inside of ``__main__.py``, it will search the current directory for valid packages first, and then if it doesn't find anything it will start searching through site-packages and pip installs. Since the current directory has a folder called ``rtv/`` with an ``__init__.py`` inside of it, that is the one that python will import.

**Comment by shanhind** [comment]
Using python -m totally fixed my problem.  I was running using python rtv/__main__.py before and for whatever reason it doesn't import from the correct place when running it that way.  Thanks for giving me a hand on this, I'm going to continue working away on adding this feature.

**Comment by shanhind** [comment]
I'm having an issue where as soon as I add a get_flair() call to content.py the program starts immediately crashing with the error message "Could not reach /r/front".  My initial thought was that an exception was being thrown and getting caught by a block that does that but I haven't been able to figure out what's happening.  get_flair documentation doesn't indicate that it would be throwing any exceptions and should just be returning None if the user or subreddit was not found.  Do you have any idea why adding get_flair calls into the split_submission method in content.py would be causing it to crash with this message?  (Note that even when get_flair is called for ANY subreddit, it always says "Could not reach /r/front")

**Comment by michael-lazar** [comment]
You're correct that the exception is getting caught where it shouldn't be. 

**content.py**, line 361
```python
content = cls(display_name, submissions, loader)                        
try:                                                                    
    content.get(0)                                                      
except:                                                                 
    # TODO: Trap specific errors                                        
    raise SubredditNameError(display_name) 
```

Try getting rid of this try-except block
```python
content = cls(display_name, submissions, loader)
content.get(0)
```
and your error should propagate through.
