### ISSUE TITLE
Split requirement

### ISSUE THREAD

**Issue by Fale** [michael-lazar/rtv#288]
Please, do split requirements between usage and testing.

**Comment by michael-lazar** [comment]
Test requirements are defined in the testing config files

- https://github.com/michael-lazar/rtv/blob/master/.travis.yml#L8
- https://github.com/michael-lazar/rtv/blob/master/tox.ini#L6

Project requirements are defined here

- https://github.com/michael-lazar/rtv/blob/master/requirements.txt
- https://github.com/michael-lazar/rtv/blob/master/setup.cfg

In that sense they're already split up. Could you please clarify what you mean?

**Comment by Fale** [comment]
Sorry, I missinterpreted some deps
