### ISSUE TITLE
Open full URL of a submission from `/` prompt

### ISSUE THREAD

**Issue by woorst** [michael-lazar/rtv#292]
As one can lanch rtv like this `rtv -l "https://redd.it/a1b2c3"` rtv should be able to open a link from it's internal prompt: `Enter page:  https://redd.it/a1b2c3`

**Comment by michael-lazar** [comment]
Thanks, this was also mentioned here: https://github.com/michael-lazar/rtv/issues/267. Agreed that it would be a nice feature to have.

**Comment by ReshefElisha** [comment]
Created a pull request that addresses this partially #314

**Comment by michael-lazar** [comment]
This feature was merged in #340
