### ISSUE TITLE
mpv hangs at 20 secs on every video

### ISSUE THREAD

**Issue by manu09** [michael-lazar/rtv#296]
So I'm using mpv to watch videos with rtv. My mailcap file looks like this:

```
video/x-youtube; mpv %s --loop=inf; test=test -n "$DISPLAY"
video/*; mpv %s --loop=inf; test=test -n "$DISPLAY"
```

I tried several videos on different subreddits and all of them stop at 20 secs. Mpv gets unresponsive then and I've to kill it with htop. When I try to open the same videos with mpv on command line, I've no issues with.

```
manu@X220 ~> uname -r                                                                                                                         13:17:40
4.7.2-1-ARCH
manu@X220 ~> rtv --version                                                                                                                    13:17:41
rtv 1.12.0
manu@X220 ~> mpv --version                                                                                                                    13:17:44
mpv 0.20.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Aug 27 12:41:39 CEST 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.3
```

**Comment by michael-lazar** [comment]
Thanks, I actually noticed this too but figured it was just a problem with mpv. Will look into it.

**Comment by michael-lazar** [comment]
Possible cause https://thraxil.org/users/anders/posts/2008/03/13/Subprocess-Hanging-PIPE-is-your-enemy/

**Comment by manu09** [comment]
Thanks alot to look into! Even though I don't use any pipe at all? :sweat_smile:

**Comment by michael-lazar** [comment]
Oh no, I mean that I use pipes here! https://github.com/michael-lazar/rtv/blob/master/rtv/terminal.py#L368 I'm still looking into how to fix it, but it looks like ``subprocess.PIPE`` is the culprit.

**Comment by goggle** [comment]
Yes, I noticed this bug too. Will it be fixed?

**Comment by michael-lazar** [comment]
Yea sorry, I've been super busy lately. I'll try to get to it soon.
