### ISSUE TITLE
link color

### ISSUE THREAD

**Issue by paoloap** [michael-lazar/rtv#299]
Hi, my terminal has dark background, and link colour on rtv is set to dark-blue (really difficult to read and ugly to see). Note that it's the only "strange" color (authors are coloured with a more bright blue).
![rtv1](https://cloud.githubusercontent.com/assets/9800389/18785229/45e17684-8197-11e6-85e6-9d25eb176bf5.png)
![rtv2](https://cloud.githubusercontent.com/assets/9800389/18785234/4d6cc304-8197-11e6-9b15-75fa59259d51.png)
Does anyone have my same issue? Is there a way to change this color? I adopt termite console.

Thanks!
P

**Comment by paoloap** [comment]
OK... I found a "workaround": I edited objects.py into /user/lib/python3.5/site-packages/rtv this way:
'BLUE': (curses.COLOR_BLUE, -1) ----> 'BLUE': (curses.COLOR_CYAN, -1)

![rtv](https://cloud.githubusercontent.com/assets/9800389/18788409/0715ad70-81a7-11e6-9998-055b5da41912.png)

Seems that the color is decided by curses python library. Does anyone know how to edit the original curses palette? :)
Thanks!
P

**Comment by michael-lazar** [comment]
Hi paoloap,

Curses will load the color pallet from the terminal that it's running on. Somewhere in your termite configuration your BLUE color is set to use that dark blue shade. So if you can figure out how to change it there, it should also apply inside of rtv.

I would try playing around with your termite config like this example
http://moparx.com/configs/termite/

color0 - black
color1 - red
color2 - green
color3 - yellow
color4 - blue
color5 - magenta
color6 - cyan
color7 - white

**Comment by paoloap** [comment]
I swear that I searched everywhere how to customize termite standard colors, thanks for the link! :)
Now I could set color4 and rtv works perfectly.

**Comment by michael-lazar** [comment]
Glad that you got it working!
