### ISSUE TITLE
Comment word wrap column

### ISSUE THREAD

**Issue by alx-k** [michael-lazar/rtv#301]
It would be really handy to be able to set the maximum comment length and word wrap there. (ie: max 80 character lines).

I frequently have my terminal applications full screen (I use a tiling window manager). `rtv` looks and feels good in full screen, but it's uncomfortable to read long comments, paragraph-like, when they take the full width of the screen.

**Comment by michael-lazar** [comment]
+1 I agree that it's hard to read comments in full-screen for this reason

**Comment by alx-k** [comment]
I've implemented this and opened a pull request. I welcome any comments on the quality of the changes, I'm trying to improve my coding skills.

**Comment by michael-lazar** [comment]
Merged in #302
