### ISSUE TITLE
Uninstall through Bash?

### ISSUE THREAD

**Issue by zAMLz** [michael-lazar/rtv#303]
Is there a way to uninstall through bash. I installed the program through that method, but now I'm looking to install via my AUR Helper so it can manage it for me. I looked at the help command of setup.py but could not find a relevant option.

**Comment by michael-lazar** [comment]
You will have to remove the files manually. Thankfully it's not that hard to do, see http://stackoverflow.com/a/1550235

**Comment by michael-lazar** [comment]
Closing because this is a python package management question and is outside of the control of what rtv can change.
