### ISSUE TITLE
[Feature request] Option to hide the username if logged in

### ISSUE THREAD

**Issue by LoLei** [michael-lazar/rtv#306]
Right now if you're logged in, it shows the username in the top right corner.

I'd like to have an option to disable that, instead just show "logged in" or something.

**Comment by michael-lazar** [comment]
Just curious, is this for privacy reasons or is there some other reason that you don't want your username displayed?

**Comment by LoLei** [comment]
Yes, for privacy.

Sometimes I'm using rtv in public (e.g. lecture hall), and I don't want people seeing my username.

Would be cool if the option to hide it existed.

**Comment by LoLei** [comment]
I just did it myself, I'll submit a PR I guess.
