### ISSUE TITLE
[Bug] Not Working Properly inside of TMux

### ISSUE THREAD

**Issue by challsted** [michael-lazar/rtv#323]
I'm running:
* TMux 2.2
* Fedora 24
* Gnome Terminal 3.20.2
* RTV 1.13.0

I am able to open, and log into RTV, but upon trying to scroll past 1 "page" of links, comments, anything that takes up more then 1 screen. Only the bottom 5-10% of the page changes. Even then, it seems to just overlay the next link or comment on top of the previous. 

This does not happen with all of the same details but minus TMux (Opening a terminal, and launching rtv works as expected)

Happy to test stuff or change things as requested. I just installed this about 10 minutes ago but couldn't find a fix. 

![rtv-tmux](https://cloud.githubusercontent.com/assets/5549965/20268502/0cdd2a0a-aa45-11e6-9b94-05430312d93b.png)

How i got the above screenshot. 
I held "j" for a few seconds, opened a random one to comments (l) returned (h) then held j for a few more seconds. 
As you can see, it goes 7-20, then 81 and 82 are stacked on top of each other at the bottom. 

@michael-lazar SS Attached as requested :smile:

**Comment by michael-lazar** [comment]
Could you post a screenshot of what you're seeing? I'm running different versions than you, but it looks like TMux is working fine for me with rtv 1.13.0.

**Comment by challsted** [comment]
Yes I can soon, at work right now. Also, forgot to mention RTV version... Ill update above when i get home +8 hours from now)

**Comment by peteyy** [comment]
I'm experiencing the same issue. I hope my screen recording helps you on this https://www.youtube.com/watch?v=TPfulmeKFUo :)

**Comment by challsted** [comment]
@peteyy Thanks! Yes, thats exactly what im experiencing

**Comment by michaelachrisco** [comment]
Looks like I ran into this bug recently with a tmux window:

tmux 2.1
rtv 1.13.0

lines get stacked when navigating through the windows. I thought that perhaps the --ascii option would work but same issue.

**Comment by michael-lazar** [comment]
@michaelachrisco Are you using fedora too?

**Comment by michaelachrisco** [comment]
In this case, I am using Ubuntu 16.04.

**Comment by xelxebar** [comment]
For whatever it's worth, I'm running rtv in tmux without any issues. Here is my version information:

    $ tmux -V
    tmux 2.3

    $ rtv --version
    rtv 1.13.0

Also likely relevant here are our various terminal emulators and TERM environment variable. Here are mine:

    $ st -v
    st 0.7 (c) 2010-2016 st engineers

    $ echo $TERM
    screen-256color

**Comment by HugoMillwood** [comment]
Same problem for me, same versions of tmux and rtv as @michaelachrisco

**Comment by michaelachrisco** [comment]
Found out something today: 

The older version of Tmux 1.8 + Ubuntu does NOT have the same issue. I also have no plugins nor mouse mode on this install of Tmux.

**Comment by michael-lazar** [comment]
Thanks for the update, it seems like the issue is isolated to certain tmux v2.x versions. I've tested a bunch of configurations with v2.3 and haven't been able to replicate the bug.

**Comment by michaelachrisco** [comment]
Ill try this on a new image of Ubuntu 16.04 + tmux and try to replicate the bug. Its also possible it has something to do with tmux customization.

**Comment by DJspy109** [comment]
I also get this bug, running the _exact_ same versions of everything as @xelxebar, except `echo $TERM` returns `xterm-256color`.

I've uploaded a pastebin of my .tmux.conf [here](http://pastebin.com/KXVmts8s). I disabled mouse mode; it didn't change anything regarding the bug.

**Comment by marius-bica** [comment]
I also confirm this bug, running tmux 1.9
What I can add to this to help is that the problem appeared in the 1.12.0 release of rtv, reverting to 1.11.0 makes it go away for me. So I guess there is some commit between tags `v1.11.0` and `v1.12.0` that is to blame.

**Comment by michael-lazar** [comment]
I was finally able to replicate the bug after loading @DJspy109 's config file. Thanks to everyone for reporting your settings!

Here's another [issue](https://github.com/fagga/transmission-remote-cli/issues/152) that I found that describes basically the same problem. Basically, it looks like tmux is unstable when the $DISPLAY is set to **xterm-256color**. Switching to **screen-256color** instantly fixed the problem for me. This advice is posted in the tmux FAQ [here]( http://unix.stackexchange.com/questions/139075).

The interesting thing, as pointed out by @marius-bica, is that this bug only appeared in ``v1.12.0``. In that release, I added the footer bar with common commands and changed the curses window positioning a little bit. Something I did must have upset the balance. Now that I can reproduce the error I'm going to investigate and see if I can patch this.

**Comment by dessalines** [comment]
For me, I had to check my `.bashrc`, and found that a script was setting my `TERM`, and removed that line. After that, my `echo $TERM` was `screen-256color`, and everything worked great.

**Comment by michael-lazar** [comment]
It looks like the underlying issue here has to do with how curses optimizes screen refreshes. Since tmux is a virtual termial, it can only support a subset of the commands that a full terminal can. That's why it uses the same [terminfo](https://linux.die.net/man/5/terminfo) entry as screen (an even older virtual terminal) to define which commands are valid. When tmux's $TERM set to xterm, curses must incorrectly assume that it has access to some command (like bce, background color erase) so it sends an invalid escape code that screws up the rendering.

I was able to fix by swapping out curses.touchwin() with curses.clearok(). The former tries to optimize drawing to the screen by only sending the characters that have changed since the previous refresh. The latter clears the memory and sends the whole screen on each refresh. I don't know exactly what this changes under the curses hood but it seems to do the trick for me.

**Comment by marius-bica** [comment]
@michael-lazar I can confirm that this fixes the issue for me. thanks!
