### ISSUE TITLE
Weird display when unfolding «More Comments» 

### ISSUE THREAD

**Issue by rpesche** [michael-lazar/rtv#327]
When I unfold «More comments», the level of next coments are shifted left.
For exemple if my folded comment are  : 

- Comment A
    - Comment A,1
        - Comment A,1,0
        - Comment A,1,1
    - Comment A, 2
    - Comment A, 3

I will have somthing like:
- Comment A
    - Comment A,1
        - Comment A,1,0
        - Comment A,1,1
 - Comment A, 2
 - Comment A, 3

I usually have this bug when I open the «Forum Libre» submission, in /r/france

**Comment by michael-lazar** [comment]
Thanks for posting this! I had noticed weird behavior with «More comments» in the past but I was never able to pin down what was triggering it. I added a test case with the comment tree that you gave as an example and sure enough it reproduced the issue. As a result, I was able to fix the bug that I introduced into the comment un-folding logic.

**Comment by rpesche** [comment]
Thanks a lot :)
