### ISSUE TITLE
[Feature Request] Custom colors

### ISSUE THREAD

**Issue by xelxebar** [michael-lazar/rtv#329]
## Overview

Currently user control over colorized output is limited to the `--monochrome` switch. It would be nice to allow user customization within the config file, mimicing functionality seen in other cli tools like [mutt][1], [newsbeuter][2] and [hangups][3] (URIs point to the relevant color configuration documentation).

## Version Info

For good measure, here is the version I am currently running:

    $ rtv --version
    rtv 1.13.0

## Example Usage

I'm envisioning something along the lines of a `[colors]` section of the configuration file where one can specify the foreground and background colors for individual "elements". Here's an off-the-cuff example:

    [colors]
    ; <element>    = <foreground> <background> <attribute>
    status_line    = black        color234
    post_title     = default      default       bold
    post_subreddit = color244     default
    post_uri       = color244     default       underline
    comment_user   = color173     default
    comment_text   = default      default
    comment_self   = color39      default

## Further thoughts

In a similar vein, perhaps it would be reasonable to also allow custom formatting of the various elements as well. This could enable RES-like functions such as user tagging, title munging, *etc.*

[//]:# (Hyperlinks)
[1]:http://www.mutt.org/doc/manual/#color
[2]:http://newsbeuter.org/doc/newsbeuter.html#_configuring_colors
[3]:https://hangups.readthedocs.io/en/stable/user_guide.html#configuration

**Comment by michael-lazar** [comment]
Thanks for the detailed summary! Colors have been attempted before, see https://github.com/michael-lazar/rtv/pull/97 and https://github.com/michael-lazar/rtv/issues/55 to get caught up. I like the idea of supporting custom themes, but in practice it has turned out to be difficult to pull off while maintaining compatibility across most terminals. I mostly blame curses for this, from what I've seen it's much easier to pull off 256 colors using plain ANSI escape sequences than trying to do it through curses' COLOR_PAIR mechanism. You're more than welcome to give it a shot though!

**Comment by girst** [comment]
This feature would be highly appreciated, because I've got the same problem as #299. (Modifying the standard terminal colors is a no-go, as that breaks all other programmes/color schemes)

Dark-Blue on black is really hard to read.

**Comment by michael-lazar** [comment]
> (Modifying the standard terminal colors is a no-go, as that breaks all other programmes/color schemes)

I'm curious how this would break other programs for you. If they use the same default dark blue shade then I assume you would have the same problem with them being hard to read.

**Comment by girst** [comment]
well, there are some things i want to be very subtle - e.g vim's column of tildes, stuff in my $PS1, ... 

but links in rtv isn't on that list ^^

**Comment by michael-lazar** [comment]
Thanks for the explanation, that makes sense.

**Comment by michael-lazar** [comment]
After 2+ years I finally got support for themes merged into the master branch! Thanks for the example configuration @xelxebar, I went with something very similar. Shoutout to @Brobin , @arount, and everyone else who worked on this back in the day.
