### ISSUE TITLE
[Feature request] Sort top by week, month, all time, etc.

### ISSUE THREAD

**Issue by TRox1972** [michael-lazar/rtv#330]
Current method, it seems, goes to `/top/`, but it'd be useful to also sort by time, e.g., `/top/?sort=top&t=all`

**Comment by michael-lazar** [comment]
1. double tap "2" to bring up the options, or
2. type in "/r/subreddit/top-all"

I'll admit it's not the most intuitive interface right now. Maybe we should auto-show the sort menu instead of making the user press "2" or "5" twice.

**Comment by TRox1972** [comment]
@michael-lazar Yes, that'd be useful.  Maybe add a config option for this?

**Comment by michael-lazar** [comment]
I went ahead and changed the default behavior to open the menu after a single press. We can test it out for a while and see if anyone complains.
