### ISSUE TITLE
Upgrade to praw >= 4

### ISSUE THREAD

**Issue by Fale** [michael-lazar/rtv#331]
As title

**Comment by michael-lazar** [comment]
Pull requests are welcome, but this would be a huge undertaking and I don't see the benefits being worth the time cost to switch over at this point.

**Comment by Fale** [comment]
I think the probl;em will be that soon many distros will upgrade to praw 4, and therefore rtv will break in those distros, forcing the maintainers to retire the package

**Comment by michael-lazar** [comment]
It looks like you're the maintainer of the package on Fedora.

Do you have an estimated time frame before things will break? Would bundling a version of praw inside of rtv be an acceptable solution? Any information that you can give from your point of view would be helpful.

**Comment by Fale** [comment]
Yes I am.
I am also the maintainer of praw in Fedora, so I can "control" when to push it, but I guess soon (few months) some other application will start requiring it and we will need to ship it.
A work around this could be to ship two different packages (python-praw and python-praw4), but is not really going to work on the long run since praw3 is not going to receive (security) fixes any longer.

**Comment by wedens** [comment]
already broken on arch linux. praw 4.1.0 in official repos

**Comment by KarlFiabeschi** [comment]
> already broken on arch linux. praw 4.1.0 in official repos.
ugly workaround is to install rtv with pip.

With last update of praw it doesn't work anymore (pip install)

**Comment by michael-lazar** [comment]
> With last update of praw it doesn't work anymore (pip install)

It should, pip keeps around old package versions. E.g. you can always do

```
pip install praw==3.6.0
```

The setup.py file pins the version < 4.0, so as long as you use pip you shouldn't have any problems. If you're mixing your dependencies with yum or apt you might run into issues though.

**Comment by KarlFiabeschi** [comment]
with a 
pip install -u rtv
now work again, thanks

**Comment by shaggytwodope** [comment]
@wedens The aur package is now fully functional.

**Comment by lillemets** [comment]
@shaggytwodope  It's actually not. I have everything up to date and still get the same (I think) error as months ago.

**Comment by shaggytwodope** [comment]
@lillemets what version is installed, do you have praw installed on the system?

**Comment by AndydeCleyre** [comment]
@shaggytwodope praw is not listed as a dep in the pkgbuild, so it's broken.

**Comment by shaggytwodope** [comment]
@AndydeCleyre NOT broken, latest rtv ships with its own praw 3. It's intended this way. Before you assume, read the release notes. @michael-lazar documents them well.

**Comment by AndydeCleyre** [comment]
@shaggytwodope sorry.

**Comment by lillemets** [comment]
@shaggytwodope I have `rtv 1.15.0-1` installed, no *praw*. Below is the last line of the error I see when attempting to run *rtv*.

    pkg_resources.DistributionNotFound: The 'mailcap-fix' distribution was not found and is required by rtv

**Comment by shaggytwodope** [comment]
@lillemets this is being addressed in https://github.com/michael-lazar/rtv/issues/357 basically, I need to know if the fixes for mailcap can be fixed or reintroduce the package. The error is entirely due to my oversight. As soon as @michael-lazar hits me up I'll re-add the package to the aur, or patch accordingly.

**Comment by lillemets** [comment]
I just updated the package (and all others) on Arch Linux and after 5 months I can use *rtv* again. Thanks!

**Comment by shaggytwodope** [comment]
@lillemets That's great. Any problems hit me up regarding aur package.

**Comment by michael-lazar** [comment]
Everything is stable and working now so I'm closing this issue. It's up to distro package maintainers to update their rtv versions and remove the praw dependency, please reach out to me if there are any issues or concerns.

The core Reddit API itself has been stable for quite a while now. The new endpoints are for things like modmail and livethreads which aren't relevant to this project. Until Reddit releases a large breaking change or a must-have feature, I don't see a compelling reason to upgrade from praw 3.
