### ISSUE TITLE
Not accepting BROWSER and RTV_EDITOR variables when using mailcap

### ISSUE THREAD

**Issue by geezuh** [michael-lazar/rtv#336]
Is there a way to define these in the mailcap?
I have verified the vars are set, but no luck.

**Comment by michael-lazar** [comment]
Could you explain the problem a little bit more? What are you trying to do exactly?

**Comment by geezuh** [comment]
I'm trying to set surf as by browser and vim as my editor.

Per the configuration section of the readme.md, I can set specific programs to launch certain types of files via the mailcap. This works with no issue.

However the next section of the readme says to set ENV variables in bash to define browser and editor. These do not work, I assume because I am using the mailcap?

If browser and editor are to be set via mailcap as well, can you add a commented out section describing how to define these in the default .mailcap?

If I say "echo $BROWSER" it returns "surf" 
Then I launch rtv from the same shell session, and hit enter on an article which then launches in Firefox.

**Comment by geezuh** [comment]
nevermind, i'm an idiot.
when I set the variables, i didn't "export" them I just set them. They still returned the proper values, but I guess they didn't carry to rtv for some reason. 

Disregard.

**Comment by michael-lazar** [comment]
No worries, I'm glad you figured it out :)
