### ISSUE TITLE
Run using docker

### ISSUE THREAD

**Issue by avindra** [michael-lazar/rtv#342]
Hi :wave: 

Seems like an interesting project. But I don't like polluting my system with global python deps.

So I'm documenting the steps to build this in docker for myself and others who may be interested.

## Setup

1) Create `Dockerfile`: (includes `less` as it's a dependency for the `help` command)

```dockerfile
FROM python:3

RUN apt-get update && apt-get install less -y && pip install rtv

CMD [ "rtv" ]

```

2) `docker build -t rtv .`

## Running 
```bash
docker run -it rtv
```

## Issues

* Figure out auth. Currently, `rtv` requires a browser for OAuth, which doesn't seem possible to do safely with docker.

**Comment by michael-lazar** [comment]
Thanks for sharing! If people are looking for for other alternatives, since the package is pure python you can always do "pip install --user" or setup a python virtualenv.

**Comment by avindra** [comment]
Nice! TIL about `--user`. Closing this issue to keep things tidy
