### ISSUE TITLE
URxvt terminal flashes everytime you go up or down an entry

### ISSUE THREAD

**Issue by Hund** [michael-lazar/rtv#343]
Is it possible to somehow prevent this from happening in rtv? I'm actually using the flash-hint-thingy feature all the time in URxvt, so I don't want to disable it in URxvt. But it gets really annoying when you browse Reddit in rtv and it flashed every time you go up/down an entry. :)

**Edit:** I assume it's the visual bell feature that's causing it? I tried lxterminal and I didn't have the issue there.

**Comment by michael-lazar** [comment]
It should only flash when you reach to first or last entry on the page and try to scroll out of bounds. If it's flashing every single time you move the cursor then something is for sure going wrong. Have you noticed any other strange behavior on URxvt? There might be an incompatibility somewhere between URxvt, your python curses build, your $TERM setting, or something else.

**Comment by Hund** [comment]
I haven't noticed anything else with URxvt.

I'm running Arch and installed it via pip due to the issue with one of the dependencies in the AUR package. 

I'm not sure where to go from here, but let me know if you need anything or want me to do anything. I'll try to debug it myself the best I can as well.

**Comment by dbaio** [comment]
Hi.
I noticed this as well on 1.14.1.
I've reinstalled rtv 1.13.0 and the flash's were gone.

**Comment by dbaio** [comment]
I was using TERM=xterm-256color, replacing to TERM=rxvt-256color not solved the problem.

Commenting out this line stopped the flash's:

https://github.com/michael-lazar/rtv/commit/f3deea5abc06f7b22830a313f90929cbd8eac0b0#diff-abdf3d507d4d4d9968cb742523b25f8fR351

**Comment by michael-lazar** [comment]
Thanks for the info @dbaio. I just installed rxvt and tested it out, here's what I observed right away: 

I did see the screen was flashing every time I scrolled, but it wasn't a visual bell. The difference is that with the actual visual bell command, the screen inverts colors for a second. But in this case it just looked like the screen was erasing and redrawing, and it was happening slow enough that it was visible to the eye. 

Does this sound like what you're seeing? If it is, it makes sense because the v1.14.1 update changed how the screen was getting redrawn and may have caused the slowdown. It's funny that this it only manifests in rxvt though (at least so far).

**Comment by dbaio** [comment]
>  it just looked like the screen was erasing and redrawing, and it was happening slow enough that it was visible to the eye.

This makes sense.

There are a lot of issues about urxvt and redraw... I will do more tests tonight at home.

https://bbs.archlinux.org/viewtopic.php?id=106412
https://bugs.freedesktop.org/show_bug.cgi?id=58843

Maybe this could help: URxvt*buffered: false

**Comment by Hund** [comment]
`URxvt*buffered: false` did not help for me. :(

**Comment by dbaio** [comment]
It didn't work. `URxvt*buffered: false` as well.

**Comment by rreno** [comment]
I'm getting the same issue with urxvt. I commented out the `self.term.stdscr.clearok(TRUE)` line and put the `self.term.stdscr.touchwin()` line back in as referenced by @dbaio [here](https://github.com/michael-lazar/rtv/commit/f3deea5abc06f7b22830a313f90929cbd8eac0b0#diff-abdf3d507d4d4d9968cb742523b25f8fR351).

I reinstalled and the screen works perfectly now with no flashing.

I might play around with conditional draw calls based on the `$TERM` environment variable and test with tmux and urxvt if you think that's worth pursuing.

**Comment by michael-lazar** [comment]
Go ahead if you're still interested. There might yet be some magical function in curses that fixes it for everyone, but until we figure that out I'm OK with using conditional logic for edge cases like this.

**Comment by BlitzKraft** [comment]
@Hund : Were you using tmux by any chance? Could you post what $TERM variable is set to?

**Comment by Hund** [comment]
@BlitzKraft No, I use a good WM instead. ;) $TERM gives me `zsh: command not found: rxvt-256color`. I should probably fix that anyway. :P

**Comment by BlitzKraft** [comment]
May be try setting $TERM to `screen-256color` or `xterm-256color` ?

**Comment by Determinant** [comment]
Same on my urxvt.

**Comment by michael-lazar** [comment]
A patch has been merged, thanks @rreno !
