### ISSUE TITLE
Open submission url after viewing comments page?

### ISSUE THREAD

**Issue by nabsiddiqui** [michael-lazar/rtv#344]
Often, I read the comments along with the post, but it seems that when you go into comments of a submission that there is no way to open the original link.  I know I can open it by going through urlview, but it would be easier to just open it directly through a keybinding.  Is there a way to do this that I am missing?

**Comment by michael-lazar** [comment]
No, I don't think that there's currently any way to do what you're looking for. Once you're in the comment view you can only open the permalink to the comments thread. 

Thanks for submitting the issue though, I'll look into adding another keybinding or possibly switching around the current behavior. From this and other feedback that I've gotten, your use case seems to be more common than wanting to open the comment permalink.

**Comment by nabsiddiqui** [comment]
Thanks for the follow up.  Yes, that would be very useful.  I actually use newsbeuter to read my reddit feed(otherwise I will just end up playing on reddit all day).  It opens the link to the comments page, but I can't then open the link for the comment itself.  Currently, I can do it through urlview, but it is a much more clunky workaround than just having a key to open the link.

**Comment by michael-lazar** [comment]
This has been added, sorry it took so long! Pressing ``o`` or ``Enter`` while the submission is selected (when the cursor is at the top of the comments page) will open the submission link.
