### ISSUE TITLE
Add setting to hide NSFW posts

### ISSUE THREAD

**Issue by averrin** [michael-lazar/rtv#347]
Please add setting to hide posts with NSFW tag

**Comment by michael-lazar** [comment]
Is there another app that does this? AFAIK there's no way to do this on the main reddit site either, except what's in https://www.reddit.com/prefs/ which just turns the nsfw labels on/off.

**Comment by averrin** [comment]
I never use reddit viewers on PC before, but my android client do can do this...

**Comment by michael-lazar** [comment]
A fix has been merged to hide NSFW posts. You will need to make sure that this option is unchecked in your reddit settings:

> I am over eighteen years old and willing to view adult content (required to view some subreddits)
