### ISSUE TITLE
Mark read posts more notable

### ISSUE THREAD

**Issue by averrin** [michael-lazar/rtv#348]
Mark read posts more notable than visited link color. Or mark unread.

**Comment by michael-lazar** [comment]
Any ideas for how to mark them? It would need to be something small and obvious because there's not a lot of screen real-estate to work with.

**Comment by averrin** [comment]
Vertical lines at comments looks good. Maybe something like this? Or colored star near title.

**Comment by mskwon** [comment]
What about a (dark) red "READ" label next to the comments counter?

**Comment by BlitzKraft** [comment]
Currently, it looks like the title text is in **bold**. To mark them read, it can be un-bolded. It would just make just enough difference with out adding too many problems. 

I use bacon reader on mobile and it does the same.

**Comment by michael-lazar** [comment]
I went with @BlitzKraft 's suggestion, thanks for the ideas and discussion.
