### ISSUE TITLE
AUR package question

### ISSUE THREAD

**Issue by michael-lazar** [michael-lazar/rtv#357]
@shaggytwodope 

I wanted to try out installing the AUR package for myself so I setup a VM using this vagrant image: https://github.com/terrywang/vagrantboxes/blob/master/archlinux-x86_64.md

The installation went fine, but when I tried to launch rtv I got this error:

```
pkg_resources.DistributionNotFound: The 'requests>=2.4.0' distribution was not found and is required by rtv
```

I looked into it and found that some of the dependencies were installed to my system's python 3.5 packages

```
/usr/lib/python3.5/site-packages/rtv
/usr/lib/python3.5/site-packages/kitchen
/usr/lib/python3.5/site-packages/six
```

But some of them were installed into python 3.6

```
/usr/lib/python3.6/site-packages/requests
/usr/lib/python3.6/site-packages/bs4
/usr/lib/python3.6/site-packages/decorator
```

I guess this is because my system's default python is 3.5, but some of the dependencies don't respect that and pin the installation into 3.6 instead? As somebody who hasn't used Arch before, is this something that I should expect yaourt to handle for me, or is this my fault for not having my default python at the latest version?

Also, I saw that you dropped the mailcap-fix dependency from the package. What was the motivation for that? rtv won't start without it

```
Traceback (most recent call last):
  File "/usr/local/bin/rtv", line 7, in <module>
    from rtv.__main__ import main
  File "/usr/local/lib/python3.4/dist-packages/rtv/__main__.py", line 19, in <module>
    from .terminal import Terminal
  File "/usr/local/lib/python3.4/dist-packages/rtv/terminal.py", line 23, in <module>
    from mailcap_fix import mailcap
ImportError: No module named 'mailcap_fix'
```

**Comment by shaggytwodope** [comment]
So I'm unsure about the VM image in use, but when updates to python are made, typically arch enforces them pretty extreme. That is to say any depends should default to newest python version. Nothing gets held back. Why you even have 3.5 unless manually installed is very odd. Only 3.6 should be available to an arch install. Save for any custom user setup of course. It is odd to see that, most cases just reinstalling an aur package would suffice to use the system default (3.6), or version bump rebuild in official repos.

I was under the impression mailcap_fix would not be needed for python3.6 which is the default for Arch. I must have installed it via pip and not thought about it. Terrible mistake on my part. There are two options here, reintroduce mailcap_fix in the aur. Or add some type of check on python version. And then only import mailcap on 3.6. Whatever you prefer fine with me. I need to check out updates on a fresh install in the future, very sorry.

**Comment by shaggytwodope** [comment]
@michael-lazar What I have in mind, would be something to the effect of this.

```
import sys
if sys.hexversion >= 0x03060000:
    import mailcap
else:
    from mailcap_fix import mailcap
```

Of course if you find it simpler to add the dependency back I can do that.

**Comment by michael-lazar** [comment]
@shaggytwodope I'll fix this on my end and push out a new release with conditional dependencies. I think in the long run that will be the better, I was avoiding it because it's kind of tricky to setup with pip.

**Comment by michael-lazar** [comment]
I just released v1.15.1 which should allow the AUR package to work without mailcap_fix.

**Comment by shaggytwodope** [comment]
@michael-lazar updated mate.

**Comment by michael-lazar** [comment]
👍
