### ISSUE TITLE
curses dependency means this doesn't work on Windows 

### ISSUE THREAD

**Issue by between2spaces** [michael-lazar/rtv#374]
The curses module is not supported on Windows machines. From the module documentation:

While curses is most widely used in the Unix environment, versions are available for DOS, OS/2, and possibly other systems as well. This extension module is designed to match the API of ncurses, an open-source curses library hosted on Linux and the BSD variants of Unix.

$ pip install rtv
Collecting rtv
  Downloading rtv-1.15.1-py2.py3-none-any.whl (132kB)
Collecting beautifulsoup4 (from rtv)
  Downloading beautifulsoup4-4.6.0-py2-none-any.whl (86kB)
Collecting decorator (from rtv)
  Downloading decorator-4.0.11-py2.py3-none-any.whl
Collecting mailcap-fix; python_version < "3.6" (from rtv)
  Downloading mailcap_fix-1.0.1-py2.py3-none-any.whl
Collecting kitchen (from rtv)
  Downloading kitchen-1.2.4.tar.gz (187kB)
Collecting requests>=2.4.0 (from rtv)
  Downloading requests-2.17.3-py2.py3-none-any.whl (87kB)
Requirement already satisfied: six in c:\python27\lib\site-packages (from rtv)
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.4.0->rtv)
  Downloading chardet-3.0.3-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests>=2.4.0->rtv)
  Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB)
Collecting idna<2.6,>=2.5 (from requests>=2.4.0->rtv)
  Downloading idna-2.5-py2.py3-none-any.whl (55kB)
Collecting urllib3<1.22,>=1.21.1 (from requests>=2.4.0->rtv)
  Downloading urllib3-1.21.1-py2.py3-none-any.whl (131kB)
Building wheels for collected packages: kitchen
  Running setup.py bdist_wheel for kitchen: started
  Running setup.py bdist_wheel for kitchen: finished with status 'done'
  Stored in directory: C:\Users\scarmody\AppData\Local\pip\Cache\wheels\f8\fb\46\3c9e9511dd9fc564c413f01ce5060392c48441ee1f82b9fc1f
Successfully built kitchen
Installing collected packages: beautifulsoup4, decorator, mailcap-fix, kitchen, chardet, certifi, idna, urllib3, requests, rtv
Successfully installed beautifulsoup4-4.6.0 certifi-2017.4.17 chardet-3.0.3 decorator-4.0.11 idna-2.5 kitchen-1.2.4 mailcap-fix-1.0.1 requests-2.17.3 rtv-1.15.1 urllib3-1.21.1

$ rtv
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\rtv.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\rtv\__main__.py", line 17, in <module>
    from .config import Config, copy_default_config, copy_default_mailcap
  File "c:\python27\lib\site-packages\rtv\config.py", line 14, in <module>
    from .objects import KeyMap
  File "c:\python27\lib\site-packages\rtv\objects.py", line 12, in <module>
    import curses
  File "c:\python27\lib\curses\__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses

**Comment by michael-lazar** [comment]
From the README

```
RTV provides an interface to view and interact with reddit from your terminal.
It's compatible with most terminal emulators on Linux and OS X.
```

Adding support for native Windows would require a huge amount of continuous effort that could be better spent on other features.  Some people have tried using cygwin with various success. I would assume that you could also use the new bash shell on Windows 10, but I haven't tested it.

I suppose that we could catch the error and print a message, to make it explicit that this is intended behavior and not a bug.

**Comment by dertuxmalwieder** [comment]
FWIW, PDCurses is a native Windows version of curses. If someone feels like working on it, it would probably be worth a try.
