### ISSUE TITLE
cbreak() returned ERR

### ISSUE THREAD

**Issue by vbmade2000** [michael-lazar/rtv#384]
Any solution why I get following error while run using subprocess.Popen() ?

`cbreak() returned ERR`

**Comment by michael-lazar** [comment]
What python version / operating system / terminal are you using?

Could you start rtv with the ``--log`` option and paste the log here after reproducing the error?

**Comment by michael-lazar** [comment]
Closing as unverified, please re-open the issue if you have further information.
