### ISSUE TITLE
[Mailcap suggestion] imgcat for iTerm2 on macOS

### ISSUE THREAD

**Issue by n055** [michael-lazar/rtv#385]
I use iTerm2 on macOS, which provides shell integration utilities, including imgcat to [display images within a terminal.](https://www.iterm2.com/documentation-images.html)

Here's my .mailcap to view images from rtv in imgcat.

```
image/*; curl -s %s | ~/.iterm2/imgcat && read -n 1; needsterminal
```

**Comment by michael-lazar** [comment]
Thanks for the suggestion!

**Comment by for-coursera** [comment]
@n055 Does it work for you with Imgur albums? Like, do you have a specific `.mailcap` entry for `image/x-imgur-album`?

Thanks!

**Comment by for-coursera** [comment]
Just in case, I've added something like this (extremely ugly, would be grateful for any suggestion):

    image/x-imgur-album; [ -d /tmp/rtv/img ] || mkdir /tmp/rtv/img && cd /tmp/rtv/img && echo %s | tr " " "\\n" >> img.txt && wget --no-check-certificate -i img.txt && rm img.txt && imgcat * && read -n 1 && rm -rf /tmp/rtv/img/* ; needsterminal
