### ISSUE TITLE
imlib2 sugestion

### ISSUE THREAD

**Issue by despin** [michael-lazar/rtv#386]
I think it would be great to integrate imlib2 for the images, with the image inside the terminal itself, as it does [ranger](https://github.com/ranger/ranger)

**Comment by michael-lazar** [comment]
A while ago, I actually took a stab at this using ``w3mimgdisplay``, which is what ranger was using at the time.

https://github.com/michael-lazar/rtv/issues/214

https://github.com/michael-lazar/rtv/compare/image_preview2#diff-9c3ca0874cc613de8742fc4310b26c5f

I got a basic concept working but it was really finicky with screen refreshes and hard to make stable enough to where it could be merged in the master branch. I ended up abandoning it to work on more pressing issues.

I haven't heard of imlib2 before, is that something different? I can't find any examples of using it to draw pictures to a terminal.

**Comment by rosshadden** [comment]
This would be really cool.  I love how well it works with projects like ranger.
