### ISSUE TITLE
Missing COPY_PERMALINK in [bindings]

### ISSUE THREAD

**Issue by frdrcv** [michael-lazar/rtv#389]
When starting rtv, I see the "logging..." box and I get the following error:
`"Invalid configuration! `COPY_PERMALINK` key is undefined"`

I'm using rtv 1.16.0 on Arch Linux, installed via the AUR.

**Comment by michael-lazar** [comment]
You probably have custom key bindings setup in your ``~/.config/rtv.cfg`` file. There was a new command added in a recent version, but its not defined in your configuration. To fix this:

1. Delete the [bindings] section in your ``~/.config/rtv.cfg``, or
2. Add the COPY_PERMALINK command to your [bindings] section

**Comment by frdrcv** [comment]
Thanks, the second solution fixed my problem.

**Comment by michael-lazar** [comment]
Glad it worked! I'm going to leave this issue open to remind myself that custom bindings need to be handled better by the code. It shouldn't break everyone configuration every time a new binding is added.
