### ISSUE TITLE
[Feature Request] Parse Markdown links and make them navigable

### ISSUE THREAD

**Issue by dweymouth** [michael-lazar/rtv#394]
It would be nice if Markdown links were displayed in colored text and navigable (Tab/Shift+Tab could select links sequentially, Enter to navigate, ESC to return to normal mode.) If the link is to another Reddit submission, open in rtv instead of the browser.

**Comment by michael-lazar** [comment]
Have you tried setting up **urlview** (the shortcut is the <kbd>b</kbd> key).

Related issues: https://github.com/michael-lazar/rtv/issues/100 https://github.com/michael-lazar/rtv/pull/240
