### ISSUE TITLE
Indicate search results page

### ISSUE THREAD

**Issue by woorst** [michael-lazar/rtv#396]
Currently it is not easy to tell the difference between looking at a page of search results or regular subreddit page with a list of submissions.

I suggest the displayed title should be something like:
`Searching
 /r/commandline: vim vs emacs`

**Comment by michael-lazar** [comment]
+1, the current search result page was sort of shoe-horned in to work with the existing subreddit page, anything that we can do to make the UI more clear would be an improvement.
