### ISSUE TITLE
Want to see more than ten imgur album pictures

### ISSUE THREAD

**Issue by allthroughthenight** [michael-lazar/rtv#399]
Looked to see if there was a way to have feh show more that ten pictures from an imgur album. Checked mailcamp setting but didn't see anything relevant. I'm guessing it's how rtv gets the images from imgur and isn't able to get the ones after the 'Load N more images'.

Possible solution is to use an album's grid view since the url only adds '?gride'? But the grid view only has previews, which have to be selected to show the full size image.

Example album below
Normal view: https://imgur.com/a/ygIZ8
Grid view: https://imgur.com/a/ygIZ8?grid

**Comment by michael-lazar** [comment]
Thanks for reporting the issue, there is actually an in-progress pull request to fix this https://github.com/michael-lazar/rtv/pull/367

**Comment by allthroughthenight** [comment]
I'll search harder next time, tired '10' 'ten' 'imgur' 'imgur more' 'imgur albums' but got no results.
