### ISSUE TITLE
rtv ignores $VISUAL when choosing a text editor

### ISSUE THREAD

**Issue by rlue** [michael-lazar/rtv#403]
Per the README:

> #### `$RTV_EDITOR`
> Composing posts and replying to comments is done using your preferred text editor. If not specified, the default system `$EDITOR` (or nano) will be used.

Any chance the author would support expanding this to check the `VISUAL` environment variable as well? I don't mean to be pedantic, and of course I should have my `EDITOR` env variable set anyway, but per [this UNIX StackExchange answer](https://unix.stackexchange.com/questions/77089/what-is-the-editor-command-in-bash):

> The `EDITOR` variable is the one you need by default for some applications to invoke the editor. There is another variable called `VISUAL` used to specify the screen-oriented editor. Generally you will want to set it to the same value as the `EDITOR` variable. Originally `EDITOR` would have be set to ed (a line-based editor) and `VISUAL` would've been set to vi (a screen-based editor).

If so, I'd be willing to take a stab at a PR. Python is not my language, but I'm sure it would be pretty trivial to figure it out.

**Comment by michael-lazar** [comment]
Thank you for creating an issue, it sounds like a reasonable thing to support. So if I understand correctly (from https://unix.stackexchange.com/a/4861), RTV should technically be checking for ``$VISUAL`` first and then falling back to ``$EDITOR`` if it isn't defined? So the new try order would be:

1. ``$RTV_EDITOR``
2. ``$VISUAL``
3. ``$EDITOR``
4. ``nano``

You're welcome to make a PR, I agree with you that this should be a very simple feature to add.

**Comment by rlue** [comment]
Ahaha, you know, I just took a look and your code is formatted so strictly, with not a single line over 82 characters long. 

If I simply extend the existing pattern, the result is 96 characters long and sticks out like a sore thumb:

   # rtv/terminal.py
            editor = os.getenv('RTV_EDITOR') or os.getenv('VISUAL') or os.getenv('EDITOR') or 'nano'

I don't know python well enough to figure out how to refactor this, and since I can't bring myself to break your very consistent style, I'm gonna leave this up to you. -_-'

**Comment by michael-lazar** [comment]
No worries, I just merged a PR so this should be taken care of.

Here's how I ended up wrapping the line if you're interested

```python
       editor = (os.getenv('RTV_EDITOR') or
                 os.getenv('VISUAL') or
                 os.getenv('EDITOR') or
                 'nano')
```

I also played around with doing it this way, but it felt more abstruse

```python
        editor = any([
            os.getenv('RTV_EDITOR'),
            os.getenv('VISUAL'),
            os.getenv('EDITOR'),
            'nano'])
```

**Comment by rlue** [comment]
Well, now, I guess it wouldn't have hurt to try after all...
