### ISSUE TITLE
Handle new native reddit videos/gifs

### ISSUE THREAD

**Issue by woorst** [michael-lazar/rtv#409]
Reddit is [rolling out](https://www.reddit.com/r/changelog/comments/6jo5it/reddit_change_introducing_video_uploading_beta/) their native video/gif hosting services.

Example link: https://v.redd.it/24bqk13lf5fz/

By appending `DASHPlaylist.mpd` the link can be handled by youtube-dl/mpv:
`mpv --autofit 640x480 https://v.redd.it/24bqk13lf5fz/DASHPlaylist.mpd`
However, I assume, this is not the case with many media players.

The `.mpd` (MPEG-DASH) format is an xml document containing data about the media file. In the above example the video and audio can easily be extracted (the numbers 9 and 6 may vary):

video: https://v.redd.it/24bqk13lf5fz/DASH_9_6_M
audio: https://v.redd.it/24bqk13lf5fz/audio

In the case of gifs the audio stream will not be present and we can simply pass the direct link to the video.

In the case of video I see the following options:
1. Assume anyone with `video/x-youtube` in their mailcap will be using youtube-dl or mpv
2. Pass the direct link of the video only stream
3. Open these video links in a graphical browser

**Comment by michael-lazar** [comment]
Thanks for the write-up. Clearly they're trying to pull traffic back from Imgur, which has gotten really aggressive at redirecting Reddit users to their own platform. The mod's comment about exposing videos through their API makes me optimistic that there might be simpler way to do this in the future. 

https://www.reddit.com/r/changelog/comments/6jo5it/reddit_change_introducing_video_uploading_beta/djfrix0/

> 1. Assume anyone with video/x-youtube in their mailcap will be using youtube-dl or mpv

I think that's fair for 95% of users. We can always implement it for now and see if anyone complains.
