### ISSUE TITLE
Support /me/m/multi format

### ISSUE THREAD

**Issue by dufferzafar** [michael-lazar/rtv#411]
When I try to enter `me/m/multi`  in the `/` prompt, I get an "invalid format" error.

Entering `/u/username/m/multi` works though.

The `/u/username` feels redundant if I'm logged in, and should be shortened by `/me`. 

Reddit website allows this too.

**Comment by BlitzKraft** [comment]
I usually use `S` to get to the multi-reddit menu and navigate from there. I didn't know about this. This is pretty neat though. 

I usually use the `/` prompt to just navigate to a specific sub.

**Comment by michael-lazar** [comment]
``me/m/multi`` I agree with your reasoning, especially if this is something that the reddit website itself supports. This should be a fairly simple pull request if somebody wants to take this on.

**Comment by dufferzafar** [comment]
@michael-lazar New to rtv and the code, but not Python. I think I can do this. Can you point me to the file that will need the changes?

**Comment by michael-lazar** [comment]
https://github.com/michael-lazar/rtv/blob/master/rtv/content.py#L463
