### ISSUE TITLE
Take reddit URLs as command line parameters

### ISSUE THREAD

**Issue by dufferzafar** [michael-lazar/rtv#412]
Should we allow taking entire URLs as parameters from the CLI?

I was viewing a thread on browser and thought of opening it in rtv but need to go through multiple steps to do that.

This is akin to just passing the URL to some cli web browser like `lynx`

**Comment by michael-lazar** [comment]
This currently works:

```
rtv -l https://www.reddit.com/r/Music/comments/6ta5j0/dead_kennedys_nazi_punks_fuck_off_punk/
rtv -l https://www.reddit.com/r/Music/comments/6ta5j0/dead_kennedys_nazi_punks_fuck_off_punk/dljbh24/
```

Was there a particular URL format that wasn't being parsed correctly, or did you not use the ``--link`` flag? This brings up a point that it might make sense to make the ``--link`` flag optional, since most people will expect it to behave like ``lynx`` ``w3m`` etc.

**Comment by dufferzafar** [comment]
I was not using the `--link` flag, but yes I agree that the flag should be optional, and `rtv` should just expect the link argument like the other tools you mentioned. This keeps behavior consistent.

**Comment by michael-lazar** [comment]
Merged, ``-l`` is now deprecated in favor of a positional ``URL`` argument.
