### ISSUE TITLE
$RTV_BROWSER not working

### ISSUE THREAD

**Issue by JPRuehmann** [michael-lazar/rtv#414]
Hello
I´ve set the Environmet Variables in my /etc/environment and rebooted.
echo Environmet Variable works
Environmet Variable at the Prompt runs
rtv Editor works but BROWSER is still firefox although the Variable says w3m.
urlview is not working to if I press b nothing happens.
Thanks,

**Comment by michael-lazar** [comment]
Hi,

1. What OS are you using?
2. How did you install RTV?
3. What version of RTV are you using? ``rtv --version``

**Comment by JPRuehmann** [comment]
Kubuntu 16.04 LTS
pip install 
1.17.1

**Comment by michael-lazar** [comment]
Try setting ``$BROWSER`` instead of ``$RTV_BROWSER``. The README documentation was recently updated and it looks like it doesn't match what's supported in v1.17.1

**Comment by JPRuehmann** [comment]
That changed nothing.

**Comment by JPRuehmann** [comment]
My failure add export $BROWSER="w3m" to /etc/environment and do a source /etc/environment it now works.
But as I understand it the $BROWSER Variable is central for all CLI Applications, and I want to use w3m only for rtv until now. so it were better if $RTV_BROWSER whould be working.
Thanks,

**Comment by michael-lazar** [comment]
``$RTV_BROWSER`` will now take priority over ``$BROWSER``
