### ISSUE TITLE
keybinding for download video

### ISSUE THREAD

**Issue by Joseph65** [michael-lazar/rtv#427]
Is there a way to keybind a command for example "youtube-dl -f 22 %s" . I know that when you press enter it opens the video with mpv, and i want to also when i press "alt + d" to execute the comand, is this possible.

**Comment by michael-lazar** [comment]
No, unfortunately there is not a way to bind keys to specific terminal commands. Everything needs to go through **.mailcap** or **BROWSER**. You could maybe solve this by using a shell script that triggers a prompt, and replacing your **mpv** mailcap entry with the shell script. Something like this should work:

```bash
#!/bin/bash

URL=$1
PS3="Please enter your choice: "
options=("Play video" "Download video")
select opt in "${options[@]}"
do
    case $opt in
        "Play video")
            youtube-dl -f 22 $URL
            break;;
        "Download video")
            mpv $URL
            break;;
        *) echo invalid option;;
    esac
done
```
