### ISSUE TITLE
Sorting by 'controversial' when viewing a submission's comments 

### ISSUE THREAD

**Issue by bongoman** [michael-lazar/rtv#432]
..pulls up the "Links from ..." menu with the 24 hours—All Time options.

There is no need for this when viewing comments?

**Comment by michael-lazar** [comment]
Thanks for posting an issue, it appears that with controversial comments it doesn't matter what the time frame is. This should be an easy thing to fix if somebody wants to take on a PR.

**Comment by michael-lazar** [comment]
Fixed, I also removed the "Links from ..." menu for sorting by top.
