### ISSUE TITLE
Crashes when text contains emojis

### ISSUE THREAD

**Issue by woorst** [michael-lazar/rtv#444]
rtv crashes when attempting to draw the following text from [this comment](https://www.reddit.com/r/ComedyCemetery/comments/701fbf/popular_guy/dmzrwbz/):

> RULE😱🤤😂🙄👌🙄🤤🔥🙌🔥👌🔥😫💦💀🤔😫🙂😫👌💦🙂😫🙂😫😂😂💦🙌😩😩😂😱🔥🙂😱💀💀🔥😩👌😤😤😫👌💪😂😂😂😳😳😩😍💪🍏😱🙏😂🙏😱🙏🙂🛫💪🛫✈️✈️🙂💀💀🙂🔥😂😱🤔🙌😩😩😤😤😤😤😤💦💦💪💪😱😱🙂🙂😱😩👌👌😱🤤😂🙄👌🙄🤤🔥🙌🔥👌🔥😫💦💀🤔😫🙂😫👌💦🙂😫🙂😫😂😂💦🙌😩😩😂😱🔥🙂😱💀💀🔥😩👌😤😤😫👌💪😂😂😂😳😳😩😍💪🍏😱🙏😂🙏😱🙏🙂🛫💪🛫✈️✈️🙂💀💀🙂🔥😂😱🤔🙌😩😩😤😤😤😤😤💦💦💪💪😱😱🙂🙂😱😩👌👌

Additionally, rtv will slow to a crawl (but not crash) when dealing with comments like [this](https://www.reddit.com/r/ComedyCemetery/comments/701fbf/popular_guy/dmzyzra/):

> 😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂😂😂😂😂😂😂😂😂😂 😂 😂 😂 😂 😂 😂 😂 😂 😂 😂

Traceback ([offending line](https://github.com/michael-lazar/rtv/blob/8b63e1c5dec87c99f68d4fec7a50049e621ebf4c/rtv/terminal.py#L275)):
```
2017-09-14 16:44:19,909:ERROR:__main__.py:216:addstr() returned ERR
Traceback (most recent call last):
  File "/home/user/builds/rtv/rtv/__main__.py", line 207, in main
    page.open_submission(url=url)
  File "/home/user/builds/rtv/rtv/subreddit_page.py", line 179, in open_submission
    page.loop()
  File "/home/user/builds/rtv/rtv/page.py", line 80, in loop
    self.draw()
  File "/home/user/builds/rtv/rtv/page.py", line 337, in draw
    self._draw_content()
  File "/home/user/builds/rtv/rtv/page.py", line 493, in _draw_content
    self._draw_item(win, data, inverted)
  File "/home/user/builds/rtv/rtv/submission_page.py", line 292, in _draw_item
    return self._draw_comment(win, data, inverted)
  File "/home/user/builds/rtv/rtv/submission_page.py", line 360, in _draw_comment
    self.term.add_line(win, text, row, 1, attr=attr)
  File "/home/user/builds/rtv/rtv/terminal.py", line 275, in add_line
    window.addstr(row, col, text, *params)
_curses.error: addstr() returned ERR
```

**Comment by michael-lazar** [comment]
Interesting, it seems to work for me on iterm2. I do notice a slight slowdown but definitely not to a crawl. The character width definitely looks inconsistent though. I wouldn't be surprised if RTV is miscalculating how long lines with emoji characters should be. I don't even know if the width of emojis is standardized across terminals.

![screen shot 2017-09-14 at 9 14 17 pm](https://user-images.githubusercontent.com/5026795/30462151-ce04a6ae-9991-11e7-9969-e090ab68d25f.png)

**Comment by woorst** [comment]
I'm have the crashing issue in both urxvt and xterm. 
The slowdown is probably because of my older hardware.

**Comment by noahfx** [comment]
I can reproduce this in Konsole Terminal Emulator but did not notice any slowdown.

**Comment by noahfx** [comment]
Hi, 
I have wrote a patch to avoid this crash  #445 , just handling the exception makes the job. 
Now I am uncertain about if the error is provoked by the curses library since after managing 
the exception the emojis are rendered (see screenshot). Seems more like the error is happening when the window attributes (rows, columns) are calculated. 

Here are the values passed to the curses.addstr function: 

```
max_cols: 134
max_rows: 28
row: 27
col: 1
attr: []

text: b'^^^^^\xf0\x9f\x98\x82  ^^^^\xf0\x9f\x98\x82  ^^^\xf0\x9f\x98\x82 ^^\xf0\x9f\x98\x82 ^\xf0\x9f\x98\x82 \xf0\x9f\x98\x82 \xf0\x9f\x98\x82^\xf0\x9f\x98\x82^\xf0\x9f\x98\x82^\xf0\x9f\x98\x82^\xf0\x9f\x98\x82^\xf0\x9f\x98\x82^\xf0\x9f\x98\x82^\xf0\x9f\x98\x82^\xf0\x9f\x98\x82^\xf0\x9f\x98\x82 ^^^^^^^^^\xf0\x9f\x98\x82 ^^^^^^^^\xf0\x9f\x98\x82  ^^^^^^^\xf0\x9f\x98\x82  ^^^^^^\xf0\x9f\x98\x82  ^^^^^\xf0\x9f\x98\x82  ^^^^\xf0\x9f\x98\x82  ^^^\xf0\x9f\x98\x82 ^^\xf0\x9f\x98\x82 ^\xf0\x9f\x98\x82 \xf0\x9f\x98\x82'


```

![screenshot_20170916_130608](https://user-images.githubusercontent.com/678185/30515149-d5f0da5a-9adf-11e7-8247-db721e0fa5e8.png)
