### ISSUE TITLE
Can you make the white titles a default terminal color?

### ISSUE THREAD

**Issue by atomi** [michael-lazar/rtv#448]
On a white background these titles don't show up. Can you set the color to just the term's default text color?

**Comment by michael-lazar** [comment]
It does use the terminal's default color (``-1``) along with the ``curses.A_BOLD`` attribute. Nothing is hardcoded to white, could you paste a screenshot of what you're seeing?

v1.18 Release:

https://github.com/michael-lazar/rtv/blob/da5e1b062cf3039b66a8b47d48b7966ba06d792d/rtv/subreddit_page.py#L269

Master Branch:

https://github.com/michael-lazar/rtv/blob/master/rtv/theme.py#L54

**Comment by atomi** [comment]
![rtv](https://user-images.githubusercontent.com/83137/31239958-c63dc360-a9b3-11e7-9265-12dd48d8d0ef.jpg)

**Comment by atomi** [comment]
Yeah this is strange. On my termux instance the title color is indeed term default. But on my workstation I use https://github.com/chriskempson/base16-shell and that might be causing this. I'll look into it a little more.

**Comment by atomi** [comment]
Yeah this is a base16 coloring issue, I'll close this for now. Sorry for the noise.
