### ISSUE TITLE
GNU Emacs terminal chokes on terminal title

### ISSUE THREAD

**Issue by toto-42** [michael-lazar/rtv#459]
When running rtv inside the terminal emulation of GNU Emacs[1], rtv tries to set the terminal title.  This makes no sense when running inside Emacs, but the terminal unfortunately doesn't fail gracefully.  Instead, the title is added to the first line which looks like this:

> 2;Front Page - rtv 1.18.0Front Page

While other lines are unaffected, the "cursor" is moved to the right to the beginning of the normal title (the "F" from the second occurence of "Front Page".

I've looked into it, IHMO a simple check if rtv is running inside GNU Emacs (the environment variable "INSIDE_EMACS" is set in this case) before creating the title in [page.py](https://github.com/michael-lazar/rtv/blob/master/rtv/page.py#L362) could prevent this.

Footnote:
[1]  In GNU Emacs, type 'M-x term', press return and then start rtv in the terminal.

**Comment by michael-lazar** [comment]
Thanks for posting the issue and doing some research into it. Your solution sounds straightforward, feel free to open a PR if you would like. Otherwise I'll try to get around to it before the next release.

**Comment by toto-42** [comment]
Sry, not a Python programmer, but thx for the quick reply.

I just added

`if not os.environ.get('INSIDE_EMACS'):`

and indentation after the

`# Set the terminal title`

comment to see if that would fix the issue.  I'm sure the system call can be done once during initialization, setting a variable controlling the behavior instead of doing this on every screen update.

**Comment by michael-lazar** [comment]
I added the check for emacs to remove the title, but there are still some weird characters beings drawn on the screen.
<img width="682" alt="screen shot 2017-11-04 at 2 36 38 pm" src="https://user-images.githubusercontent.com/5026795/32408414-c2fce510-c16d-11e7-93b2-2d3b27b7cbf2.png">

**Comment by michael-lazar** [comment]
Good explanation of the issue with emacs ansi-term: https://github.com/fish-shell/fish-shell/issues/2441

**Comment by michael-lazar** [comment]
Fixed by updating my emacs version, ``brew install emacs``, this looks ready to merge now
