### ISSUE TITLE
Buku integration

### ISSUE THREAD

**Issue by maln0ir** [michael-lazar/rtv#465]
Add a way to use [buku](https://github.com/jarun/Buku) (or any other bookmarking tool) to save submission/permalink.

Currently, rtv can save submissions on Reddit using `w` key. Consider using `W` key to save submission using configurable external tool.

**Comment by michael-lazar** [comment]
Thanks for the suggestion.

**Comment by maln0ir** [comment]
[Second try](https://gitlab.com/ajak/tuir/issues/25/) :)
