### ISSUE TITLE
Switching to non-existent subreddit crashes and throws a praw exception

### ISSUE THREAD

**Issue by Brobin** [michael-lazar/rtv#47]
I tried switching to /r/django and mispelled it djagno. This threw an exception and exited the program. Perhaps there is a better way to handle this?

```
praw.errors.RedirectException: Unexpected redirect from http://www.reddit.com/r/djagno/.json?limit=1024 to http://www.reddit.com/subreddits/search.json?q=djagno
```

Maybe we could catch the redirect exception and show the subreddit search, or just go to the first sub that shows up in that search.

**Comment by michael-lazar** [comment]
Whoops, this is supposed to show a popup notification instead of crashing. Thanks for the heads-up! Fixed in 68f30b2e07d97e19754ea90cb9d0701fe5623c60, upped version to 1.1.1
