### ISSUE TITLE
Use rtv with MacOS preview?

### ISSUE THREAD

**Issue by wheelsofsteel** [michael-lazar/rtv#470]
Firstly, apologies if this isn't the place to ask questions. Secondly, is there any way to configure rtv to open images/albums with "preview" in MacOS? I'm currently using xquartz/feh and it's a bit cumbersome!

**Comment by michael-lazar** [comment]
This is a great place to ask questions like this! Here's a duplicate issue that brings up MacOS preview. Feel free to continue the discussion there. https://github.com/michael-lazar/rtv/issues/413
