### ISSUE TITLE
Word wrapping in $PAGER for long text

### ISSUE THREAD

**Issue by jupart** [michael-lazar/rtv#474]
Currently, rtv pipes text for a submission, comment, etc. directly into $PAGER (like `less`). `less` breaks lines based on length, ignoring/not caring if it breaks a word. I'd like to add functionality to break lines without breaking words, I'm thinking about piping the text into `fold` and piping that into $PAGER. Comments, opinions, objections?

**Comment by michael-lazar** [comment]
I like the idea. RTV already has the capability to wrap text based on words, in fact it probably does a better job that ``fold`` because it's aware of unicode-wide characters. It might be easier to do this in python.
