### ISSUE TITLE
Question mark symbols surrounding comments

### ISSUE THREAD

**Issue by wheelsofsteel** [michael-lazar/rtv#475]
https://imgur.com/a/xr16J

For some reason I am getting question marks surrounding comments (in both iTerm and default terminal), not sure how to fix it. Running OS X El Capitan.

**Comment by michael-lazar** [comment]
What shell are you using? It looks like your ``$TERM`` variable is set incorrectly.

Also check that your locale is defined:

```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by wheelsofsteel** [comment]
I'm using bash; "echo $TERM" returned "xterm-256color". Locale is defined as "en_GB.UTF-8" (which makes sense, as I'm English), will changing it help?

**Comment by michael-lazar** [comment]
Hmm, all of those setting sound appropriate. 

From your screenshot it looks like there is a lot more going wrong than just the question marks. The screen isn't being refreshed, text is getting jumbled and printed in the wrong place, etc.

RTV uses the ncurses library to send characters to the terminal. Usually what happens is that if your terminal isn't configured correctly, ncurses will try to use the wrong [terminal codes](http://wiki.bash-hackers.org/scripting/terminalcodes) and you end up with corrupt text like you're seeing.

**Comment by michael-lazar** [comment]
Closing due to lack of information
