### ISSUE TITLE
$RTV_BROWSER - How to assign browser - Newbie Question

### ISSUE THREAD

**Issue by karaagac** [michael-lazar/rtv#476]
Hi. 
I want to use opera as my browser when opening  imgur and wikipedia links. So how do I set opera as my default browser for rtv only. Meaning where do I add $RTV_BROWSER = opera or whatever the command is. 

Thank you.

**Comment by michael-lazar** [comment]
It's an environment variable, you can define it like this when you launch rtv:

```
$ env RTV_BROWSER=opera rtv
```

If you want to save the value permanently so you don't need to keep typing it, you need to stick it in a file. This can be a little different depending on what operating system you're using.  For example, on macOS you could add this line to your **~/.bash_profile**

```
export RTV_BROWSER=opera
```

https://unix.stackexchange.com/questions/21598/how-do-i-set-a-user-environment-variable-permanently-not-session

**Comment by karaagac** [comment]
Great Thank you for the response.

I added it to my zshrc (in my Linux mint ) and tried it. It opens opera but gives an error. 
For example http://openurl%28https//i.imgur.com/27H7UxS.gifv,new-page)

What am I doing wrong?

Thank you again.

**Comment by michael-lazar** [comment]
Hmm I don't know why it isn't working. The python stdlib method claims to support Opera, but it appears that your URL is getting mangled. https://docs.python.org/3/library/webbrowser.html#webbrowser.get

If you're running the python 2 version of RTV, you might want to try uninstalling and re-installing the python 3 version. It's possible that there was a fix that didn't get backported to python 2.

```
sudo python2 -m pip uninstall rtv
sudo python3 -m pip install rtv
```

**Comment by karaagac** [comment]
Thank you for your answer, Michael.

I uninstalled and reinstalled it as python3, as you wrote above, but the same thing is happening. :( 

Thank you though.

**Comment by ralpheeee88** [comment]
having the same issue albeit trying to use w3m as my blowser

**Comment by karaagac** [comment]
w3m is great with rtv but the source of my problem is different actually. The problem is, Wikipedia and Imgur are weirdly blocked in Turkey, where I live, and there are many posts linked to Imgur and Wikipedia. Opera has built-in VPN service and I made it default. If I direct any link to opera, it opens it in VPN mode and I can see the post that is censored for now. That is the only reason I want to use opera otherwise good old Firefox is my default.

**Comment by michael-lazar** [comment]
@karaagac I was able to confirm the error that you're seeing by installing opera on my Arch Linux machine. It appears that there's either a bug in the python standard library or the opera browser command line. I didn't dig into it deep enough to figure out the root of the issue, but I've patched RTV so it should work with opera now.

**Comment by karaagac** [comment]
@michael-lazar I tried and it works. Thank you. I appreciate it.
