### ISSUE TITLE
Option to disable screen flashing entirely

### ISSUE THREAD

**Issue by GloverDonovan** [michael-lazar/rtv#478]
Is there any way to disable the flash when you scroll up and there's nothing else to scroll up to? I couldn't find anything for it in `rtv.cfg`.

I looked at #343 but what I want to do is get rid of flashing entirely. A toggle for it would be great.

Thanks

**Comment by michael-lazar** [comment]
Would it be sufficient to globally disable the visual bell through your terminal settings? Or is there something about RTV's usage in particular that you don't like?

**Comment by GloverDonovan** [comment]
I wouldn't mind if rtv showed a message like "Reached the end of the page" or "Already at the start of the page" instead of flashing the screen. The inverted colors aren't that great to look at with the config I use.

I looked through the man pages for my terminal [termite](https://github.com/thestinger/termite/) and couldn't find an option to disable the visual bell. I don't know of any programs that flash the screen like rtv does, so I never had a need to disable it.

**Comment by nemanjan00** [comment]
@GloverDonovan 
Try putting 

```
visible_bell = false
```
in ``[options]`` section of ``~/.config/termite/config``

**Comment by GloverDonovan** [comment]
@nemanjan00 Thanks for the reply!

I added `visible_bell = false` to my `~/.config/termite/config` and started a new termite process but unfortunately still receive flashing in rtv.

I also tried turning off the visual bell in urxvt, but when I read the man pages it's supposed to be off by default.

```yaml
URxvt.mapAlert:     false
URxvt.urgentOnBell: false
URxvt.visualBell:   false
```

termite v13
urxvt v9.22

For anyone else that has this problem, here's a temporary workaround:

```shell
sudo sed -i "s/curses.flash()/None/g" /usr/lib/python3.6/site-packages/rtv/terminal.py
```

This gets rid of the flashing in rtv. Make sure to replace the file location with where you installed rtv.

**Comment by nemanjan00** [comment]
@GloverDonovan tbh, I did not test if that changed anything but that is how to disable visualBell in termite...

**Comment by CK9a5ISZ** [comment]
Hello, I have the same problem but with "Konsole".

I don't have any idea if it's even possible to disable screen flashing.
Are there any options in the config to disable this annoying behavior?

Thanks.

**Comment by jenewein** [comment]
Thanks GloverDonovan for the nice solutions. As there are people in this world that suffer from epilepsy I would love to see this becoming an option in rtv.
