### ISSUE TITLE
Stuck with 80x25 size when spawning from qutebrowser

### ISSUE THREAD

**Issue by The-Compiler** [michael-lazar/rtv#480]
Hey! I'm the maintainer of [qutebrowser](https://qutebrowser.org/) and set up a keybind to start rtv from it.

However, when I do so (e.g. via `:spawn termite -e rtv`), I get the content in 80x25 even if I resize the terminal:

![image](https://user-images.githubusercontent.com/625793/33284751-622db0ac-d3b0-11e7-9bd6-1205aa5e99a5.png)

Do you have any idea what could be causing this, or how to debug this? I first thought it was because how qutebrowser launches things via PyQt, but this works fine:

```
python3 -c "from PyQt5.QtCore import QProcess; proc = QProcess(); proc.start('termite', ['-e', 'rtv'])"
```

so I'm really out of ideas right now...

edit: Looks like it happens with xterm and termite, but not st or urxvt. Other applications (like neomutt) seem fine.

**Comment by michael-lazar** [comment]
RTV gets the screen size using [curses.getmaxyx()](https://docs.python.org/2/library/curses.html#curses.window.getmaxyx), which is a binding to [this function](https://linux.die.net/man/3/getmaxyx).

I would try running ``tput lines`` / ``tput cols`` from your process, I think they use the same method as curses to determine the screen size. Check the environment variables that Qt passes to the process: that ``$LINES`` and ``$COLUMNS`` aren't hardcoded, and that ``$TERM`` is appropriate for the terminal that you're using.

https://stackoverflow.com/a/38536991
https://unix.stackexchange.com/a/93176

**Comment by The-Compiler** [comment]
If I do `:spawn termite -e /bin/bash`, I get the correct values, and starting rtv from there works as expected.

If I do a quick hack to get a pdb prompt with `/pdb` in rtv and take a look there (with it spawned directly), indeed `os.environ['LINES']` and `COLUMNS` are set to 24/80 and `self.term.stdscr.getmaxyx()` is `(24, 80)`.
