### ISSUE TITLE
README.md references undesirable Arch package `yaourt`

### ISSUE THREAD

**Issue by ThrosturX** [michael-lazar/rtv#482]
Very nitpicky, but I'd very much prefer `README.md` would reference a different AUR helper than `yaourt`, since it is pretty much ubiquitously considered one of the worst AUR helpers of today.

Looking at the [Comparison Table](https://wiki.archlinux.org/index.php/AUR_helpers#Comparison_table), I would suggest replacing the `yaourt` reference with something such as `pacaur` (which uses the same syntax as `pacman`, as does `yaourt`), simplifying the modification in `README.md` to a single word substitution.

**Comment by michael-lazar** [comment]
I'm deferring to @shaggytwodope , he's the maintainer of the AUR packages

**Comment by shaggytwodope** [comment]
No worries simply replacing, pacaur is a fine AUR helper.

**Comment by michael-lazar** [comment]
The README has been updated to use ``pacaur``.
