### ISSUE TITLE
[Feature Request] Tab Complete subreddits at / prompt

### ISSUE THREAD

**Issue by wrhansen** [michael-lazar/rtv#485]
It would be nice if the `/` prompt could include tab completion for subreddits. I can't remember all the subreddits I visit so it would be nice to be provided with some sort of feature that lets you see them through tab completion.

If it isn't possible with the *all* subreddits because of the shear amount of them, it would make sense to see this feature for subreddits you subscribe to.

**Comment by michael-lazar** [comment]
Agreed this would be a nice enhancement, I think this is similar enough to https://github.com/michael-lazar/rtv/issues/236 to mark it as a duplicate issue though, please continue any discussion there.
