### ISSUE TITLE
Images from imgur-gallery not sorted correctly when viewing in eog

### ISSUE THREAD

**Issue by armandg** [michael-lazar/rtv#486]
When opening a imgur-gallery in ~~feh~~ eog, the images are not saved in the same sequence as in the gallery.
Most probably because images are saved with the same name as in the gallery (seven random letters and numbers).

Tested with imgur-gallery in [this submission](https://www.reddit.com/r/NintendoSwitch/comments/7hz4km/dear_mr_iwata/).

I'm really not sure how the images are processed or saved, but if they are saved on disk, the filenames should be appended with a number first: `https://i.imgur.com/KXrAJMx.jpg` -> `01 - KXrAJMx.jpg`

**Comment by michael-lazar** [comment]
What's your mailcap entry look like? It appears to preserve the order of images for me using the default example:
```
image/x-imgur-album; feh -g 640x480 %s; test=test -n "$DISPLAY"
```

**Comment by armandg** [comment]
Ooooh, sorry, brainfart here:

I forgot I had changed the viewer to eog, so I had this setting:
`image/x-imgur-album; eog %s; test=test -n "$DISPLAY"`

When testing with the default setting with feh, it works like a charm.

As I was trying to use existing apps, any tips on how to make eog sort the images?

**Comment by michael-lazar** [comment]
Looks to be a long-standing limitation with eog

https://www.bountysource.com/issues/1075428-eog-doesn-t-respect-the-way-nautilus-has-ordered-the-pictures

You could probably get creative with curl+xargs and write a command or even a small script that fetches the URLs, renames them, saves them to a temp directory, and opens that directory in eog.

**Comment by armandg** [comment]
I might have a look at it. Where is the code for fetching imgur-galleries?

**Comment by michael-lazar** [comment]
https://github.com/michael-lazar/rtv/blob/master/rtv/mime_parsers.py#L214

**Comment by armandg** [comment]
Cheers, I'll see what I can do.

**Comment by armandg** [comment]
@michael-lazar After having a look at it, I have to admit that I'm not even close to understand how this script works, since I consider myself an amateur Pythoneer. My solution was installing feh.

But thanks for the replies and the pointers.
