### ISSUE TITLE
[Close] rtv change theme, Unrecognized arguments : --theme

### ISSUE THREAD

**Issue by xxzozaxx** [michael-lazar/rtv#490]
I want to said Thank You form my <3, for this awesome CLI app. 

but I have a little program with change themes when I type 
`rtv --theme molokai`
I get
`rtv: error: unrecognized arguments: --theme`
_
I have molokai file in `.config/rtv/themes/`
my rtv version **rtv 1.20.0**
my OS is ** Arch Linux**

**Comment by shaggytwodope** [comment]
Themes are not in any release yet. You can try the rtv-git package if you want these features asap.

**Comment by xxzozaxx** [comment]
yeah, It don't mensiond in README.md or in THEME.md
Good lucky I wait it
