### ISSUE TITLE
Put history.log and refresh-token in $XDG_DATA_HOME

### ISSUE THREAD

**Issue by calebperkins** [michael-lazar/rtv#491]
The `~/.config/rtv/refresh-token` and ` ~/.config/rtv/history.log` files could be written to `$XDG_DATA_HOME` (or possibly `XDG_CACHE_HOME`) instead of `$XDG_CONFIG_HOME`. It's a common practice to version control the config directory, and the XDG specification makes this distinction between config and data files, which change more regularly.

**Comment by michael-lazar** [comment]
This has been implemented
