### ISSUE TITLE
[Suggestion] A Command To Go Back to User's Front Page

### ISSUE THREAD

**Issue by mekhami** [michael-lazar/rtv#5]
This may be possible via visiting a subreddit alias that I'm not aware of, but it'd be nice to have a simple command to go back to the front page, currently if I navigate to a subreddit I have to exit and login again.

**Comment by michael-lazar** [comment]
I had already put this in there with the alias "front", e.g. /r/front. The documentation should probably be made more clear.

**Comment by michael-lazar** [comment]
Updated documentation
