### ISSUE TITLE
[Suggestion] New keybinding for opening links

### ISSUE THREAD

**Issue by Brobin** [michael-lazar/rtv#50]
I have been user rtv for a few days now and I have primarily been using the arrow keys to navigate the pages. I think it would be useful to bind the 'enter' key to open links in addition to the 'o' key. This makes it much easier for browse for those of us using the arrow keys.

**Comment by Brobin** [comment]
Made a pull request #51

**Comment by Brobin** [comment]
Hmm, it seems like curses' `KEY_ENTER` isn't working correctly

**Comment by michael-lazar** [comment]
Merged
