### ISSUE TITLE
Cannot login from the Windows Subsystem for Linux

### ISSUE THREAD

**Issue by Emily1799** [michael-lazar/rtv#501]
I understand if this isn't currently supported, but is there any workaround I can use? For reference I am on Ubuntu 16.04.3 LTS. When I try to login, I get a "Redirecting to Reddit" box, but nothing happens -- I would assume it's trying to open a browser and failing?

Thanks

**Comment by michael-lazar** [comment]
Unfortunately I have no experience with this, but here are some things that come to mind

- Verify that you can open your web browser (firefox, chrome, etc) directly from the linux command line. 
- Try installing a terminal based browser like lynx or w3m, and set ``$BROWSER`` to point to that before launching.

**Comment by michael-lazar** [comment]
Closing the issue, feel free to open if you have further questions

**Comment by LoZeno** [comment]
Hello,

I've encountered a similar issue, but I can proceed further than @Emily1799 :
I am using Lynx as my text browser; when I try to login, I get directed to the login page correctly; after giving username and password (and 2FA code) I'm redirected to the page to approve RTV's access to my account; clicking "Approve" causes the error "Alert! Unexpected network read error".

Checking what URL is the browser trying to access, it's `http://127.0.0.1:65000/state=<omissis>`, as expected; curl-ing that url returns `Empty reply from server`

**Comment by michael-lazar** [comment]
Hi @LoZeno 

The RTV process launches a local HTTP server on port ``127.0.0.1:65000`` to handle OAuth redirections. It looks like you can't connect to that server; it could be firewall, antivirus, something else weird with WSL that's blocking you. I would try launching a standalone http server i.e.

```
python3 -m SimpleHTTPServer 65000
```

and see if you can curl that.

**Comment by LoZeno** [comment]
Hi @michael-lazar ,

yeah, I tried that half an hour after I posted my comment: I have an Apache HTTP server running on WSL (for development) and it works fine (can curl, can access the webpages with Lynx and with Chrome from the Windows env.); running the Python SimpleHTTPserver, instead, does not give the same results, the server is running but CURL returns "empty reply from server".

It's likely some issue in the way WSL works.
