### ISSUE TITLE
Change the fallback editor from `nano` to `busybox vi` or `busybox ed`.

### ISSUE THREAD

**Issue by pthfdr-42** [michael-lazar/rtv#507]
`nano` is not installed on every PC.
However, BusyBox is installed on nearly every Linux PC since it is required to generate a new initial RAM FS, and it provides a `vi` and an `ed` applet.
Also, on embedded systems, BusyBox is the only feasible option.

**Comment by michael-lazar** [comment]
On CentOS 7

```
$ busybox vi
-bash: busybox: command not found
```

On MacOS 10.12

```
bash-4.4$ busybox vi
bash: busybox: command not found
```

Do you have a concrete use case for what you're describing? I would expect that any system incapable of running nano would also be incapable on running the python/curses packages required for ``rtv``.

**Comment by pthfdr-42** [comment]
Use case: Some people get `vi` (or `vim` or other terminal editors) installed and `nano` purged since they do not want multiple programs doing the same thing.Some minimal systems use Busybox for lower resource consumption.
Also, on Debian, the default editor is usually not set by `$EDITOR` but by a symlink `/etc/alternatives/editor`, so the detection does not work.You should acknowledge that.

**Comment by pthfdr-42** [comment]
It seems that there is no response from the developers.
I changed `nano` to `sensible-editor` and problem solved.
