### ISSUE TITLE
I get readTimeouts really often?

### ISSUE THREAD

**Issue by NikosEfthias** [michael-lazar/rtv#512]
Whenever i leave the session long enough when i try to refresh the page or post something i get readTimeouts. 
I am on macosx high sierra

**Comment by michael-lazar** [comment]
Does this look like the same error that you're seeing?

https://github.com/michael-lazar/rtv/issues/469

**Comment by NikosEfthias** [comment]
exactly

**Comment by michael-lazar** [comment]
Closing as duplicate issue
