### ISSUE TITLE
[Feature Request] Add cancel keybinding to cut operations in half

### ISSUE THREAD

**Issue by NikosEfthias** [michael-lazar/rtv#514]
Sometimes some operations take too long it would be really nice to be able to cancel them

**Comment by michael-lazar** [comment]
You should be able to press the <kbd>Esc</kbd> key any time there is a "loading..." type window in the screen. Have you tried that, or are there certain cases where that doesn't work?

**Comment by michael-lazar** [comment]
Closing as resolved, please reopen if you have any further questions about this behavior.
