### ISSUE TITLE
Links do not open correctly

### ISSUE THREAD

**Issue by liamhendricks** [michael-lazar/rtv#517]
Hey guys,

Having an issue getting rtv to open links. I haven't seen this behavior documented anywhere so I opened an issue. Essentially anytime I ty to open a link, a new empty chrome window is opened, but I am not taken to the page. Same with attempting to login to reddit with 'u'. Does not work in tmux or outside of tmux in a regular iTerm2 window.

Using: tmux 2.6, rtv 1.12.0, macOS high sierra, 10.13.3, zshell 5.4.2, inside iTerm2.

My tmux conf is pretty bland, no plugins:

> set-window-option -g mode-keys vi
set -g prefix C-a
unbind C-b
set -sg escape-time 1
bind \ split-window -h
bind - split-window -v
bind r source-file ~/.shell-config/tmux \; display "Reloaded!"
set -g default-terminal "screen-256color"
set-option -g pane-border-fg colour235
set-option -g pane-active-border-fg colour240
set-option -g message-bg black
set-option -g message-fg brightred
set-option -g status on
set -g status-interval 5
set-option -g status-bg colour235
set-option -g status-fg yellow
set-option -g status-attr dim
set-window-option -g window-status-fg brightblue
set-window-option -g window-status-bg colour236
set-window-option -g window-status-attr dim
set-window-option -g window-status-current-fg brightred
set-window-option -g window-status-current-bg colour236
set-window-option -g window-status-current-attr bright
set -g status-left-length 70
set -g status-left "Liam Hendricks "
set -g status-right-length 60
set -g status-right "#[fg=blue]#S #I:#P #[fg=yellow]:: %d %b %Y #[fg=green]:: %l:%M %p :: #(date -u | awk '{print $4}')::"
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R
bind < resize-pane -L 10
bind > resize-pane -R 10
bind = resize-pane -U 10
bind + resize-pane -D 10
setw -g mode-keys vi

I have unmodified rtv.conf.

I installed rtv with home brew.

**Comment by michael-lazar** [comment]
Thanks for the bug report. 

Try running ``osascript -e 'open location "https://www.reddit.com"'`` and see if that opens a blank page. That should be the same as the command that rtv is calling internally (unless you set a custom browser using the ``$RTV_BROWSER`` or ``$BROWSER`` environment variables). If the osascript command fails, it means there's probably an issue with your macOS default web browser configuration.

**Comment by liamhendricks** [comment]
Thanks for the reply.

That command does not open the link successfully either. I did a bit more testing and switching my default browser to safari opens the link without a problem. Could just be an issue with chrome, I'll have to dig in. But I'll go ahead and close this issue since the problem is not because of rtv
