### ISSUE TITLE
Disable quit confirmation?

### ISSUE THREAD

**Issue by for-coursera** [michael-lazar/rtv#528]
May be I'm missing something but is there any way to disable quit confirmation? Sure, I can use `force quit` but that doesn't sound right, does it? :)

**Comment by michael-lazar** [comment]
*Force quit* is the appropriate thing to use of you don't want the confirmation dialog. You can activate it using <kbd>Shift + q</kbd> or <kbd>Ctrl + c</kbd>. If you don't like holding down the shift key, you could always rebind the quit key in the config so that <kbd>q</kbd> maps to *Force quit*.
