### ISSUE TITLE
"Opening page in a new window" blocks the user interface - qutebrowser

### ISSUE THREAD

**Issue by magnetophon** [michael-lazar/rtv#546]
Would it be possible to keep rtv responsive when opening a page?
My browser (qutebrowser) takes quite some time, in fact it always times out rtv.

**Comment by michael-lazar** [comment]
Qutebrowser is kind of a niche browser, and it's possible that it's just not being handled correctly by Python's webbrowser library. It should be registered as a "background browser", which means that rtv will open it in a separate thread and return immediately.

See here, it will probably need to be added to this list:
https://github.com/michael-lazar/rtv/blob/master/rtv/objects.py#L38
