### ISSUE TITLE
colorblind theme

### ISSUE THREAD

**Issue by indiabarulfootball** [michael-lazar/rtv#547]
hello. it is hard for me to use rtv bececause of my color blind. is it possible to have a colorblind theme? i have green colorblind. i think doing all colorblinds is good if possible for everyone.

**Comment by michael-lazar** [comment]
Hello, thanks for starting this issue!

What kind of features are you looking for in a colorblind theme? Would it be something simple like changing green to yellow or another color? Are there guidelines that we can follow?

Also, keep in mind that the default rtv theme will use your terminal's default colors. So another option might be to change your terminal color configuration.
