### ISSUE TITLE
HTTPError when voting on archived post

### ISSUE THREAD

**Issue by Pepedou** [michael-lazar/rtv#548]
When pressing a/z on archived post an HTTPError message is shown. After accessing the post from the browser I noticed it was archived and it isn't possible to upvote/downvote the post anymore. I think rtv should alert when a post is archived.

**Comment by michael-lazar** [comment]
Thanks for posting an issue, this is an interesting edge case that hasn't been considered yet.

**Comment by KaKi87** [comment]
Hey, I'm experiencing the same issue but I get an `HTTPException` instead. Thanks
