### ISSUE TITLE
[Feature Suggestion] Color themes

### ISSUE THREAD

**Issue by Brobin** [michael-lazar/rtv#55]
Subreddits like [/r/itsaunixsystem](http://www.reddit.com/r/itsaunixsystem) have cool hacker custom css. I think it would be cool to implement some sort of theming for either the whole system, or for specific subreddits. This could be implemented using the .rtv file and allowing users to override the colors if they'd like. Thoughts?

**Comment by Brobin** [comment]
It might also be a good idea to fix the color naming conventions to allow for color schemes. For example `color.CYAN` is spread all throughout the code. more descriptive names would allow for more customization, perhaps like this.

```
_colors = {
    'FLAIR':        (curses.COLOR_YELLOW, -1),
    'UPVOTE':       (curses.COLOR_ORANGE, -1),
    'UPVOTE':       (curses.COLOR_CYAN, -1),
    'COMMENT_1':    (curses.COLOR_MAGENTA, -1),
    'COMMENT_2':    (curses.COLOR_CYAN, -1),
    'COMMENT_3':    (curses.COLOR_GREEN, -1),
    'COMMENT_4':    (curses.COLOR_YELLOW, -1),
}
```

Then there's also the issue with terminals not allowing more than the 8 basic colors. [This stackoverflow post](http://stackoverflow.com/questions/13060139/how-can-i-get-more-colors-curses-python-terminal) has a few suggestions for getting around this and deciding if the terminal supports the full 256 colors using the `TERM` value. Then if the extra colors aren't supported, it could fall back to a default.

**Comment by michael-lazar** [comment]
I think this would be a good start. Watch out for the [*COLOR_PAIRS*](https://docs.python.org/2/library/curses.html#curses.start_color) constant. I haven't looked to far into it, but I got the impression that terminals most that only support 8 colors also only support 8 color pairs. In that case, having separate pairs for ``FLAIR`` and ``COMMENT_4`` for example won't work.

**Comment by Brobin** [comment]
Since many terminals only have 8 colors I'm going to close this for now.

Also, most people can tweak the "theme" enough by setting their terminal's default foreground and background.
