### ISSUE TITLE
vimeo mailcap

### ISSUE THREAD

**Issue by wtfdewuno** [michael-lazar/rtv#561]
how do i edit the mailcap config so that vlc or mpv streams vimeo videos instead of having the browser automatically launched directly to the website and having the video played from there. 
and it would be nice if there were a discord server specifically for rtv

**Comment by michael-lazar** [comment]
There's no scraper for vimeo videos yet ([mime_parsers.py](https://github.com/michael-lazar/rtv/blob/master/rtv/mime_parsers.py)), so unfortunately they will show up as normal html pages. If anybody wants to create a PR for this, it should be a pretty easy addition.

**Comment by michael-lazar** [comment]
And there's no discord, but if you want to chat you can leave a message in [gitter](https://gitter.im/michael-lazar/rtv) and the people subscribed to the room will get an email.

**Comment by woorst** [comment]
It is not possible to get a direct link to the video stream from the vimeo html source. Should we just pass it with the `video/x-youtube` mimetype so people with mpv/youtube-dl can play the video?

**Comment by michael-lazar** [comment]
@woorst sounds like a reasonable solution for now, thanks!
