### ISSUE TITLE
README should not advice pacaur but yaourt

### ISSUE THREAD

**Issue by pyluyten** [michael-lazar/rtv#566]
For Arch users : the README says to run pacaur. But according to this arch wiki page, this is problematic : https://wiki.archlinux.org/index.php/AUR_helpers

So README could instead say to run `yaourt -S rtv` or just point to repology.

**Comment by pyluyten** [comment]
ouch sorry. So, i would just point to the AUR package without precising any instruction (after all the AUR wiki page does not tell to use any helper), but you are more qualified to decide.

**Comment by michael-lazar** [comment]
I'll keep it as ``pacaur`` for now, and leave the issue open so others can weigh in.

**Comment by jathanasiou** [comment]
Both `pacaur` and `yaourt` have issues as of now. The completely secure options are (in the order listed in arch wiki):

- aurman
- aurutils
- pakku
- pikaur
- trizen
- yay
- bauerbill


Out of these `aurman`, `trizen` and `bauerbill` can also be used as full pacman replacements while the former also fetches PGP keys automatically based on the table there. Personally, I've been using `pakku` as it pulls AUR comments as well, but its build syntax can be a bit cumbersome compared to yaourt/pacaur.  

Manjaro has also developed the graphical [pamac](https://gitlab.manjaro.org/applications/pamac).

**Comment by mrcpj1998** [comment]
Adding on to this. Don't get dragged down in managers and politics, just point to rtv aur package

**Comment by pabloariasal** [comment]
It is the norm to just provide a link to the package in the AUR, every single Arch user will know how to proceed. As @mrcpj1998 suggests, AUR installation instructions are pointless specially if they include unmaintained tools.

**Comment by RakNoel** [comment]
Adding this: [https://www.reddit.com/r/archlinux/comments/7k5suz/pacaur_now_unmaintained/](url)

It might be time to change that, as it might be misleading for new arch-users. 

Whatever you do recommend is probably not all that important. Id say either do a) "yay rtv-git" becuase "yay" sounds fun and worked for me, b) simply give a link to the arch-wiki about AUR-helpers, or c) so like @meskarune and just make them build it. :package: 

Id go with yay :1st_place_medal:

**Comment by Almamu** [comment]
I'd do the same as @pabloariasal and @mrcpj1998 said, give a link to the aur package. I would add a link to the aur documentation on archlinux just in case, but nothing more.

**Comment by michael-lazar** [comment]
Thanks for the feedback everyone. @Crestwave pointed out that RTV was recently moved out of the AUR and into [community](https://www.archlinux.org/packages/community/any/rtv/
). Given that, I think this discussion is now moot because I don't think anyone can argue against the legitimacy of using ``pacman``.
