### ISSUE TITLE
[Feature] Show gold symbol next to gilded comments

### ISSUE THREAD

**Issue by Brobin** [michael-lazar/rtv#57]
I think this would be a nifty little feature. Just like in the browser, show a little icon next to a gilded comment. I didn't see anything in the praw documentation about `comment.gilded` but it is a property of the [reddit api comment](https://github.com/reddit/reddit/wiki/JSON#comment-implements-votable--created).

`u'\u2B24` ⬤ with `Color.YELLOW` would work nicely

Something like this.

```
│AlphaX • 299 pts 9hr ⬤x1
│What CSS feels like
│
│Edit: holly shit my first gold! I'm rich! I'll take two art please. Thanks
│mistery man.
```

**Comment by michael-lazar** [comment]
Have you seen these ones?

✰	``U+2730``
✪	``U+272A``

**Comment by Brobin** [comment]
Oh, nice! The circle with the star is much better.
