### ISSUE TITLE
Page-Up crashing rtv sometimes

### ISSUE THREAD

**Issue by rand0MPrecisi0n** [michael-lazar/rtv#576]
Hello and thanks for your time,

I've been getting Page-Up crashes every once in a while, with the following error:

> Traceback (most recent call last):
>   File "/usr/bin/rtv", line 11, in <module>
>     load_entry_point('rtv==1.21.0', 'console_scripts', 'rtv')()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
>     return self.resolve()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/lib/python3/dist-packages/rtv/__main__.py", line 242, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3/dist-packages/rtv/__main__.py", line 225, in main
>     page.loop()
>   File "/usr/lib/python3/dist-packages/rtv/page.py", line 82, in loop
>     self.controller.trigger(ch)
>   File "/usr/lib/python3/dist-packages/rtv/objects.py", line 590, in trigger
>     return func(self.instance, *args, **kwargs)
>   File "/usr/lib/python3/dist-packages/rtv/subreddit_page.py", line 179, in open_submission
>     page.loop()
>   File "/usr/lib/python3/dist-packages/rtv/page.py", line 80, in loop
>     self.draw()
>   File "/usr/lib/python3/dist-packages/rtv/page.py", line 361, in draw
>     self._draw_content()
>   File "/usr/lib/python3/dist-packages/rtv/page.py", line 499, in _draw_content
>     self.nav.flip((len(self._subwindows) - 1))
>   File "/usr/lib/python3/dist-packages/rtv/objects.py", line 489, in flip
>     assert n_windows >= 0
> AssertionError

From what I can recall it always happens from inside a thread as opposed to a sub's "lobby". It's very rare, once in a hundred presses or less. I'm using Linux Mint 19 with xfce4 terminal 0.8.7.3 and rtv 1.21

Thanks for looking into it, cheers!

**Comment by michael-lazar** [comment]
Hi, thanks for the bug report! Looks like an edge case that needs to be handled better. The page-up / page-down code is kind of messy in general.

**Comment by michael-lazar** [comment]
Closing because I have been unable to replicate on newer versions of RTV. If somebody else encounters this bug, please feel free to leave a comment and re-open the issue.
