### ISSUE TITLE
[Feature Request] sudo rtv used public key for ssh authentication 

### ISSUE THREAD

**Issue by arkohanim** [michael-lazar/rtv#577]
Hey I don't even know if this is possible, but would it be possible for users to setup a public key and use ssh authentication for login. If this works you wouldn't need to use a web browser.

**Comment by michael-lazar** [comment]
Unfortunately, part of OAuth is that you need to make an HTTPS connection directly to the reddit server in order for them to send you an auth token. AFAIK they don't allow anything other than typing in your username / password into their web form. The good thing is that once you have done this once, the auth token will be valid forever as long as you don't logout.
