### ISSUE TITLE
Missing _curses.so?

### ISSUE THREAD

**Issue by warshanks** [michael-lazar/rtv#578]
I tried to update my rtv to the latest version with pip and now I get this error. I've made no changes to my python and I tried reinstalling the older version to no avail. I'm using python 3.6.5 on KDE Neon. 

`Fatal Error: Your python distribution appears to be missing _curses.so.
Was it compiled without support for curses?`

**Comment by michael-lazar** [comment]
Do you have two versions of python installed on your system? My guess is that when you first installed RTV (through your package manager?), it was linked to your system python which had curses available. But then when you tried to upgrade using pip, the ``pip`` command was associated with a different python runtime that was compiled without curses.

**Comment by warshanks** [comment]
Well I went back and checked and I don't think I installed it through apt-get or anything like that... But I do have Python 2.7.12 and 3.6.5 installed. Any help is appreciated I'm new to this whole python thing. Thank you for your patience.

**Comment by michael-lazar** [comment]
Try this

```
$ python3 -m pip uninstall rtv
$ python2 -m pip install rtv --upgrade --force-reinstall
```

**Comment by warshanks** [comment]
That worked! Thank you so much.
