### ISSUE TITLE
Key shortcut to refresh current subreddit - Add documentation

### ISSUE THREAD

**Issue by SamTebbs33** [michael-lazar/rtv#585]
It would be useful to have a key shortcut that would refresh the current subreddit, e.g 'r'. This would mean you don't have to do '/r/...' when you just want to refresh the subreddit you're viewing at the time.

With some guidance I'd be very happy to implement this myself and submit a PR.

**Comment by michael-lazar** [comment]
This is already a feature, you can refresh the page with <kbd>r</kbd> or <kbd>F5</kbd>

**Comment by SamTebbs33** [comment]
Ah ok, this should probably be added to the shortcut bar at the bottom.
