### ISSUE TITLE
[issue] Bad request when attempting login - vimb

### ISSUE THREAD

**Issue by Cur10** [michael-lazar/rtv#591]
when you attempt to log in the user is taken to a page saying that there is an invalid client id 

tried on arch with both the aur package and with the pip package

![screenshot](https://user-images.githubusercontent.com/42315368/44001096-36d3d0f8-9de0-11e8-8a71-6da9ea43fe1d.png)

**Comment by michael-lazar** [comment]
I just checked and it's still working fine for me. If you have a custom configuration file (**~/.config/rtv/rtv.cfg**), I would double check that the client ID didn't get changed. It should match the default value in the repository:

https://github.com/michael-lazar/rtv/blob/36b9353236acc11be208c4cee2191b9854c9625c/rtv/templates/rtv.cfg#L63-L65

**Comment by Cur10** [comment]
the issue was with the browser I was opening it with, vimb has issues with reddit apparently but firefox does'nt
