### ISSUE TITLE
Support opening links from a comment

### ISSUE THREAD

**Issue by codesoap** [michael-lazar/rtv#593]
It would be cool if it were possible to open links, that are mentioned in the comments.

Remark: I'm already working on a proposal for an implementation.

**Comment by michael-lazar** [comment]
See previous discussions here:

https://github.com/michael-lazar/rtv/issues/100
https://github.com/michael-lazar/rtv/pull/240
https://github.com/michael-lazar/rtv/issues/394

Currently you can accomplish this using the ``urlview`` key shortcut, which will pipe the text to an external application. If you can come up with a better solution that's built in to RTV and still provides a good user experience, I'm all for it!

**Comment by michael-lazar** [comment]
Feature has been merged
