### ISSUE TITLE
[Feature Request] Ability to save/unsave post.

### ISSUE THREAD

**Issue by mac1202** [michael-lazar/rtv#600]
Hello I can access my saved post using u/saved. But I can't find a way to save new post or to unsave them. It would be very useful if this could be added.
Another little ting that would be great is that when going to an user profile only the overview is available. That mix all the post and comment that the user make and is not very practical to use. Most android app propose two other sections,  posted (to show only the post the user make) and comment (for the comment). It would be great to also have this section in rtv.
Thank you.

**Comment by woorst** [comment]
This is already possible. The [default binding](https://github.com/michael-lazar/rtv/blob/v1.24.0/rtv/templates/rtv.cfg#L136) is`w` to (un)save.

As to your second point, that is a good idea. One should be able to go to seperate pages like this: `u/spez/posts` `u/spez/comments`. While `u/spez` defaults to the overview page.

**Comment by michael-lazar** [comment]
RTV now supports separate URLs to distinguish between comments and submissions

```
/u/me/overview (both comments and submissions)
/u/me/submitted
/u/me/comments
```
