### ISSUE TITLE
Mark edited submissions/comments

### ISSUE THREAD

**Issue by woorst** [michael-lazar/rtv#612]
Add an asterisk next to the created time of a message.

Perhaps additionally note the time of the edit if it differs significantly from the created time.

**Comment by michael-lazar** [comment]
👍  sounds like a solid improvement

**Comment by woorst** [comment]
Which would be better fomat, a simple asterisk or something more verbose?
```
35925 pts • 6hr* - 2146 comments
35925 pts • 6hr(edit 4hr) - 2146 comments
```

**Comment by michael-lazar** [comment]
I agree, I like the second one better
