### ISSUE TITLE
HTTP timeout (with proxy?)

### ISSUE THREAD

**Issue by rogershieh** [michael-lazar/rtv#623]
Hello,

I tried both the brew and python (3.7) version but both fail to load with a http timeout. I have to use a socks5 proxy to access reddit at all so I can't test rtv without it. Is the local web server implementation of rtv incompatible with proxies?

**Comment by michael-lazar** [comment]
How are you using your proxy to connect?

https://github.com/michael-lazar/rtv/issues/522

**Comment by rogershieh** [comment]
I gave that a try, launching with these:
```HTTPS_PROXY="socks5://127.0.0.1:1086" rtv
HTTPS_PROXY="socks5://localhost:1086" rtv```
but I get InvalidSchema for both

**Comment by rogershieh** [comment]
Working now, thanks for the help! Maybe put this in the documentation?
