### ISSUE TITLE
[Feature Request] Downloading posts from Text based subreddits once a week and storing in txt formats

### ISSUE THREAD

**Issue by Pac23** [michael-lazar/rtv#635]
Reddit is a waste of time,atleast the non-knowledgeable subreddits are. I am proposing a new feature that will download all the posts of the day and downloads in a textbase/evernote format.

 I want to work on this.I was originally going to make a separate app but then this being integrated with an already present reddit cli app would be awesome.

**Comment by michael-lazar** [comment]
Scraping reddit is outside of the scope of this project. There are several other tools out there for downloading reddit content, or you can easily write your own using praw. Either way would likely be easier than trying to build what you need on top of RTV.
