### ISSUE TITLE
XDG Specification

### ISSUE THREAD

**Issue by Ram-Z** [michael-lazar/rtv#65]
Follow [XDG specs](http://standards.freedesktop.org/basedir-spec/basedir-spec-0.7.html#introduction) and read the config file in the following order:

* `$XDG_CONFIG_HOME/rtv/rtv.conf`
* `~/.config/rtv/rtv.conf` (in case XDG_CONFIG_HOME is not set)
* `.rtv` (for compatibility reasons)

**Comment by Reihar** [comment]
What about "config" as a filename?

**Comment by Ram-Z** [comment]
Sure, the name of the file is not specified by XDG, so anything sensible is fine.

Since configparsers format is very similar to INI, `rtv.ini` would also be appropriate.

**Comment by michael-lazar** [comment]
I'm open to a pull request for this
