### ISSUE TITLE
Soooo good project but I am in China

### ISSUE THREAD

**Issue by jinfagang** [michael-lazar/rtv#652]
For some well to know result in China the reddit can not access, but I can access google and reddit in brower:

![image](https://user-images.githubusercontent.com/21303438/52839425-1101cd00-3131-11e9-99bd-11e27f43d27e.png)

**Comment by michael-lazar** [comment]
1. launch rtv with logging enabled ``rtv --log rtv.log``
2. paste the contents of the ``rtv.log`` file here
