### ISSUE TITLE
Texts become messy when scrolled up after scrolling down a bit using tmux.

### ISSUE THREAD

**Issue by DrDonkey** [michael-lazar/rtv#662]
See the following image:
![2019-03-10-114045_1366x768_scrot](https://user-images.githubusercontent.com/18498932/54081441-30a1a500-432d-11e9-92b5-7ee50fb2cd94.png)

Without tmux it is fine._(is this tmux issue?)_
A bit irritating.
I am using termite.
rtv is installed from official repo of manjaro using pacman. rtv version is `rtv 1.24.0`.
`echo $TERM` spits xterm-termite inside tmux.

**Comment by michael-lazar** [comment]
Yes this is a tmux issue, see the [tmux FAQ](https://github.com/tmux/tmux/wiki/FAQ). In short, you shouldn't be overriding your ``TERM`` to ``xterm-termite`` when running inside tmux. There's no way to fix this in RTV (that I've found), without breaking other, valid terminal configurations.

**Comment by DrDonkey** [comment]
Okay. No need to keep this issue opened.
