### ISSUE TITLE
soft-code application data path (it's hard-coded to ~/.local/share/rtv)

### ISSUE THREAD

**Issue by libBletchley** [michael-lazar/rtv#666]
**Is your feature request related to a problem? Please describe.**
The application data path is hard-coded to `~/.local/share/rtv`.  When that path is a symbolic link to the user's preferred location, [firejail](https://github.com/netblue30/firejail) breaks due to a bug in firejail (it cannot handle symbolic links).  The secure workaround for that bug is to force the app to access the non-symbolic path.  But `~/.local/share/rtv` is hard-coded.

The insecure workaround is for firejail to allow access to all files, which comes at the cost of security.  This workaround works with no changes to RTV.

**Describe the solution you'd like**
Firejail's bug is not RTV's problem.  But it's still wrong to hard-code paths.  Users should always be in control of how their filesystem is organized.

**Comment by michael-lazar** [comment]
It's not hardcoded, that path is defined by your ``$XDG_DATA_HOME``

https://github.com/michael-lazar/rtv/blob/master/rtv/config.py#L23

**Comment by libBletchley** [comment]
I suspected that, but then I did `env | grep XDG` and got nothing useful.
