### ISSUE TITLE
Add option to open browser links in new window

### ISSUE THREAD

**Issue by pabloariasal** [michael-lazar/rtv#669]
I use a tiling window manager where I have a dedicated workspace only for rtv and usually have other browser instances opened in different workspaces. 

rtv always opens a new tab in an existing browser instance instead of opening a new browser window. Hence, I'm forced to change workspaces and look for the browser instance where the page was opened.

Ideally one could set a configuration parameter to alter this behavior (i.e. always open a new window instead of a new tab). This issue is related to #506, but less complex, as one may continue to use `webbrowser` module with a different call.

I would like to issue a pull request for this, if my proposed solution seems reasonable.

**Comment by michael-lazar** [comment]
I think this is a reasonable solution. I don't think that it's significant enough to add a new command line flag, but a ``rtv.cfg`` setting makes sense.  Go for it!
