### ISSUE TITLE
[Bug] UnicodeEncodeError when replying to a post or comment that has unicode characters - Python 2.7

### ISSUE THREAD

**Issue by Brobin** [michael-lazar/rtv#67]
On python 2.7, if you try to respond to a comment that contains unicode characters, it crashes ([reddit comment](http://www.reddit.com/r/linuxmasterrace/comments/314xdt/browse_reddit_from_your_glorious_terminal_xpost/cpyz3zl))

stack trace
```
File "build/bdist.linux-x86_64/egg/rtv/submission.py", line 42, in loop
  File "build/bdist.linux-x86_64/egg/rtv/page.py", line 140, in trigger
  File "build/bdist.linux-x86_64/egg/rtv/submission.py", line 98, in add_comment
UnicodeEncodeError: 'ascii' codec can't encode character u'\u15e7' in position 129: ordinal not in range(128)
```

Could not replicate on Python 3.4

**Comment by Brobin** [comment]
Replicated again with the following:

```
rtv -l http://www.reddit.com/r/linuxmasterrace/comments/316in4/even_rpcmasterrace_knows_you_should_be_running/
```

**Comment by Brobin** [comment]
I think the issue might be formatting the string before calling the clean method

Changing line 148 of submission.py
```python
text = clean('{flair} '.format(**data))
```
To this
```python
text = '{0} '.format(clean(data['flair']))
```
Resolves the problem.

**Comment by michael-lazar** [comment]
Yup you're right, I just figured this out as well.

Calling ``'{flair}'.format(**data)`` in python2 tries to convert the unicode data to a native string before formatting it. You need to explicitly mark the type as unicode.
```python
clean(u'{flair} '.format(**data))
```
09c4865. Thanks for the detailed bug report.

**Comment by Brobin** [comment]
Looks good. I'm glad I could help :+1:
