### ISSUE TITLE
apostrophes replaced with question marks

### ISSUE THREAD

**Issue by Xohwie1i** [michael-lazar/rtv#679]
See the second sentence of the top comment in the following [screenshot](https://imgur.com/a/VjGDNgz). It reads "I?m trying to resolve...." instead of "I'm trying to resolve...". 

This issue might be related to this old one [here](https://github.com/michael-lazar/rtv/issues/475).

Below is some system information that might be helpful. Anyway, thanks for a great application!
   ```
 $ echo $TERM
    st-256color
```
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME=en_DK.UTF-8
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES=C
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

```
$ rtv --debug-info
rtv version: rtv 1.26.0
rtv module path: /usr/lib/python3.7/site-packages/rtv/__main__.py
python version: 3.7.3 (default, Mar 26 2019, 21:43:19)  [GCC 8.2.1 20181127]
python executable: /usr/bin/python
praw version: packaged, commit 1656ec224e57
locale, encoding: LC_CTYPE=en_US.UTF-8;LC_NUMERIC=en_US.UTF-8;LC_TIME=en_DK.UTF-8;LC_COLLATE=C;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=C;LC_PAPER=en_US.UTF-8;LC_NAME=en_US.UTF-8;LC_ADDRESS=en_US.UTF-8;LC_TELEPHONE=en_US.UTF-8;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATION=en_US.UTF-8, UTF-8
Environment Variables
  BROWSER         : qutebrowser
  DISPLAY         : :0
  EDITOR          : vim
  LANG            : en_US.UTF-8
  PAGER           :
  RTV_BROWSER     : /home/david/unix/scripts/networking/my_private_qutebrowser.sh
  RTV_EDITOR      :
  RTV_PAGER       :
  RTV_URLVIEWER   :
  TERM            : st-256color
  VISUAL          : vim
  XDG_CONFIG_HOME : /home/david/.config
  XDG_DATA_HOME   : /home/david/.local/share

```

**Comment by michael-lazar** [comment]
From the screenshot, it looks like rtv is running in ``ascii=True`` mode. I can tell because the bullet points are ``o`` instead of ``•`` . There are typically three ways that this can happen:

1. You're passing in the ``--ascii`` flag
2. You have ``ascii = True`` set in your *~/.config/rtv/rtv.cfg* file
3. You're locale is misconfigured (but it looks like it's ``UTF-8``, so that should be fine)

**Comment by Xohwie1i** [comment]
Setting `ascii = False` in the config file fixes the issue, thank you! And also thanks for letting me know about my locale misconfiguration, I'll have to take a look into this.

**Comment by michael-lazar** [comment]
> And also thanks for letting me know about my locale misconfiguration, I'll have to take a look into this.

Sorry for the confusion, I meant that if your locale *was* misconfigured, it might explain the behavior that you were seeing. Your environment looks correct to me!

**Comment by Xohwie1i** [comment]
Ah, ok, good to know. And again, rtv is awesome, thanks for all your hard work!
