### ISSUE TITLE
Typo in Help

### ISSUE THREAD

**Issue by MarkusPettersson98** [michael-lazar/rtv#680]
## Bug
The [Basic Commands] listing on the help page of rtv shows wrong information regarding moving the cursor up and down in rtv. Currently, it says the following: 
```
 j     : Move the cursor up
 k     : Move the cursor down
```

This is a clear typo, since rtv actually uses vim bindings for moving the cursor up and down (j for cursor down, k for cursor up). This is even more evident when looking at the following binding

```
m     : Move the cursor up one page
```
Which moves the cursor to the top of rtw, or in the same direction as pressing k.

This bug is present in both `CONTROLS.md` and `docs.py`.

## How to reproduce
1. Start rtv
2. Press "?"

## Proposed fix

```
 j     : Move the cursor down
 k     : Move the cursor up
```

**Comment by michael-lazar** [comment]
Yup I definitely got them mixed up, nice catch
