### ISSUE TITLE
[Meta] Documentation of Releases

### ISSUE THREAD

**Issue by Brobin** [michael-lazar/rtv#71]
Not a huge issue, but it might be nice to document release a bit more. Github has a nice [release feature](https://help.github.com/articles/creating-releases/).

**Comment by michael-lazar** [comment]
Done :)
https://github.com/michael-lazar/rtv/releases

**Comment by Brobin** [comment]
I updated the readme to reflect theses changes as well. And fixed it up as well :) #79
