### ISSUE TITLE
rtv not using config file

### ISSUE THREAD

**Issue by ThaWeatherman** [michael-lazar/rtv#76]
I created `~/.config/rtv/rtv.cfg` with my username and password in it as shown in the README. However when I run rtv then try and comment it tells me I need to be logged in to do that. Why would it not be reading my config file?

**Comment by Brobin** [comment]
Is your `$XDG_CONFIG_HOME` set to something that is not `~/.config/`?

**Comment by ThaWeatherman** [comment]
Nope it is not set

**Comment by Brobin** [comment]
Interesting. This was just updated in a pull request yesterday. Does the fallback file `~/.rtv` work as expected?

**Comment by ThaWeatherman** [comment]
I did not know there was a fallback file. Do I set the values in there in the same way?

**Comment by Brobin** [comment]
Yeah the same way. This was how the config worked in 1.1. It was left in there to keep things compatible. I'll look into the issue with the config folder.

**Comment by michael-lazar** [comment]
Hi. If you've installed using ``pip install``, check the README at https://pypi.python.org/pypi/rtv/. There have been some recent changes on the github branch that are not yet active in the pip version.

**Comment by ThaWeatherman** [comment]
Oh maybe that is it then. I guess I could install the development version. When will it be updated with pypi?

**Comment by Brobin** [comment]
You can also install the new version with pip like this.

```
pip install git+https://github.com/michael-lazar/rtv.git
```

**Comment by ThaWeatherman** [comment]
Will I be able to update to the latest version that way without using git?

**Comment by ThaWeatherman** [comment]
Also using `.rtv` instead of `~/.config/rtv/rtv.cfg` solved the problem

**Comment by michael-lazar** [comment]
Heads up, the pypi version just got upped to v1.2.

The default behavior is now to search ``~/.config/rtv/rtv.cfg`` first, and then fall back to ``~/.rtv``. Please let me know if you experience any problems with this in the future.
