### ISSUE TITLE
404 error when posting comment

### ISSUE THREAD

**Issue by ThaWeatherman** [michael-lazar/rtv#77]
This has happened 3 times now. I post a response to someone's comment and the application dies with a 404 error. Are there relevant log files for me to show you to help diagnose the issue?

**Comment by Brobin** [comment]
There aren't any log files. Did it give you a stack trace?

**Comment by ThaWeatherman** [comment]
No unfortunately it just said 404 not found

**Comment by yskmt** [comment]
I think it happens when RTV does not update the comments and you try to reply on deleted comment.

**Comment by Brobin** [comment]
That sounds right. The comment would not be found, triggering the HTTPError

(118-119, `__main__.py`)
```python
except requests.HTTPError:
    print('HTTP Error: 404 Not Found')
```

**Comment by ThaWeatherman** [comment]
Both times I have restarted rtv afterwards and the comment I was replying to still existed

**Comment by Brobin** [comment]
Hmm, that's interesting. Are you sure your internet connection wasn't spotty? If you disconnected temporarily it would also trigger this error.

**Comment by michael-lazar** [comment]
@ThaWeatherman, I just added some extra logging for posting comments. Please grab the most up-to-date version of RTV and start the program with the following flag
```bash
rtv --log /tmp/rtv.log
```
Then if you experience any errors, paste the contents of the logfile here. Thanks for your help!

**Comment by michael-lazar** [comment]
Closing as unable to reproduce. If you have any new relevant information, please feel free to reopen the issue.
