### ISSUE TITLE
No way to get to /top or /new

### ISSUE THREAD

**Issue by tobywhughes** [michael-lazar/rtv#8]
When entering in the subreddit name, there is no way to go to the subreddit's top or newest posts (e.g. reddit.com/r/python/top). It looks like its because the way subreddit names are submitted is by name instead of by URL. It looks like it could be fixed by having a way to catch if /top or /new are present when parsing the url and just return something besides sub.get_hot() here. https://github.com/michael-lazar/rtv/blob/master/rtv/content.py#L315

**Comment by michael-lazar** [comment]
I think this is a good idea. It looks like there are similar functions for new, hot, top, controversial, and rising. I like the idea of appending to the subreddit url as opposed to adding a bunch of key bindings for each sorting method. I'll leave this open for a little while in case anybody wants to provide a pull request.

**Comment by tobywhughes** [comment]
I'm seeing if I can make something work.

**Comment by tobywhughes** [comment]
Submitted the pull request.

**Comment by michael-lazar** [comment]
Done. I think there's room to expand upon this in the future, including sorting by controversial and sorting submission comments. Should also add a note in the readme.
