### ISSUE TITLE
Automatically open self post in comments when opened.

### ISSUE THREAD

**Issue by 5225225** [michael-lazar/rtv#88]
If I press o or enter on a self post, it loads the comments in the default browser. We can view comments fine, so opening a self post should be equivalent to opening the comments of the self post.

**Comment by michael-lazar** [comment]
I'm unsure what you mean by this. `o` is currently mapped to "open the selected link in a new web browser tab". Are you saying that this shouldn't be the case?

**Comment by Brobin** [comment]
I think he is pressing 'o' in the subreddit view and expecting it to open the submission view of the comments instead of the browser

**Comment by 5225225** [comment]
Yes, if it's a self post, the `url` is set to the comments page of the post. Opening that should open it in the program itself, instead of using a browser.

I made the changes in my own fork, but I don't know if it's the best way, as I changed `open_link` to check if the selection is a self post, and calling `self.open_submission`. There might be a cleaner way to do this.

**Comment by michael-lazar** [comment]
Ok I understand now, thanks for elaborating. I appreciate hearing different viewpoints about how people are using the program. That being said, I'm not a huge fan of this suggestion. Here are the reasons why:

1. `l` is already available and does exactly what you're asking for.
2. IMO having the `o` key do two disjoint things is more confusing to explain to people.
2. In some cases you might actually want to actually open the comments in your browser, I don't want to take that option away.

**Comment by michael-lazar** [comment]
Closing for now, please reopen if you have additional info or ideas to add.
