### ISSUE TITLE
Allow users to submit upvotes and downvotes

### ISSUE THREAD

**Issue by michael-lazar** [michael-lazar/rtv#9]
Users who are logged in should be able to vote on submissions and comments. I think the following keybinds would work:

u - upvote
d - downvote
c - clear vote

Applying the vote should be fairly easy, something like
```
submission_data = content.get(index)
submission_data['object'].upvote()
```

This would also entail adding a visual cue to indicate which items the user has voted on.

I'll leave this open in case anybody wants to work on it.

**Comment by mekhami** [comment]
It's possible you could consider using the same keybindings for upvoting/downvoting that RES uses. Also you could remove the need for a 'clear vote' command by using upvote to clear an existing upvote. It's a little more conditional logic but fewer commands is preferrable from a design perspective IMO.

**Comment by michael-lazar** [comment]
I hadn't considered that, do you have a link to the default RES bindings? I agree that I would rather follow conventions that people are already using instead of trying to invent something new.

**Comment by mekhami** [comment]
For Future Reference: 

http://reddittricks.blogspot.com/2013/11/reddit-enhancement-suite-keyboard.html

I'm gonna try to implement upvoting and downvoting now. I'll submit a PR tonight or tomorrow morning.

**Comment by michael-lazar** [comment]
Good luck!

**Comment by mekhami** [comment]
@michael-lazar As part of writing this I was considering adding a vote_status attribute to the submission class. It's already a PRAW method.

The reason I'm considering this is I can't seem to clear votes.

https://github.com/mekhami/rtv/blob/master/rtv/subreddit.py#L37-L47

This is the code I have so far which does accurately submit upvotes and downvotes. And if you upvote a downvoted post, it changes to an upvote. but it does not clear upvotes when i hit a on an upvoted post.

(If you made it through those sentences, kudos.)

I'm not sure why this is. Maybe you can shed some insight?

**Comment by michael-lazar** [comment]
I would check if casting a vote is actually changing the local copy of PRAW `Submission` object. My guess is that `Submission.likes` is not getting updated. Calling `refresh()` forces `SubredditContent` to reload all of the Submissions from the server.

**Comment by mekhami** [comment]
@michael-lazar that's SubredditPage.refresh()? Does that re-download the content? I'd hate to have to re-download and re-draw the content every time I wanted to upvote or downvote.

**Comment by michael-lazar** [comment]
Yes and yes. You shouldn't have to redownload, you just need to update the local copy after placing a vote.

Something like this (not tested):
```python
def upvote(self):
    data = self.content.get(self.nav.absolute_index)
    success = data['object'].upvote()
    if success:
        data['vote_status'] = 'upvote'
```
Then when you go back later to check the state:
```python
data = self.content.get(self.nav.absolute_index)
state = data['vote_status']
```

This will require adding a `'vote_status'` field to the content dict. Check out `content.BaseContent.strip_praw_submission`, you will need to add a line in there.

**Comment by mekhami** [comment]
It seems like PRAW has neglected to implemented the 'likes' attribute of the Reddit API. I'm gonna take a look at implementing it, but for now this feature is obviously on hold.

**Comment by mekhami** [comment]
Well, I was wrong about the previous, it's just not in the PRAW docs but the Reddit API has the likes attribute still.

The code here is not working, really. 
https://github.com/mekhami/rtv/blob/master/rtv/subreddit.py#L110-L129

I think I still have the 'once per page reload' problem.

**Comment by michael-lazar** [comment]
```python
    def upvote(self):
        submission = self.content.get(self.nav.absolute_index)
        if submission['likes'] == True:
            self.clear_vote()
        else:
            submission['object'].upvote()
        submission['likes'] = True
```
That last line needs an extra tab. You don't want to set `'likes'` to true after you clear the vote!

**Comment by mekhami** [comment]
Yeah I fixed that almost immediately after I saw that but it still isn't functioning the way I expect it to and I can't puzzle out way.

**Comment by michael-lazar** [comment]
Post an updated commit and I'll take a look at it.

**Comment by mekhami** [comment]
https://github.com/mekhami/rtv/blob/master/rtv/subreddit.py

**Comment by michael-lazar** [comment]
What are you expecting to happen? How are you checking that the upvote/downvote was actually applied?

**Comment by mekhami** [comment]
Right now I'm simply checking in my browser logged into the same account. Later, I'll have a visible marking for things that are upvoted or downvoted. But I'm not getting repeated commands to function at all.

**Comment by michael-lazar** [comment]
Try this, paste the following at the top of main.py
```python
import logging
logging.basicConfig(level=logging.DEBUG, filename='rtv.log')
```
This will redirect all of the logging output from the requests module into a file. You can then monitor changes to the file by opening up a second terminal and typing 
`tail -f rtv.log`

When I did this, my log file started to look something like
```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): ssl.reddit.com
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/login/.json HTTP/1.1" 200 None
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.reddit.com
DEBUG:requests.packages.urllib3.connectionpool:"GET /user/civilization_phaze_3/about/.json HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"GET /.json?limit=1024 HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/vote/.json HTTP/1.1" 200 2
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/vote/.json HTTP/1.1" 200 2
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/vote/.json HTTP/1.1" 200 2
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/vote/.json HTTP/1.1" 200 2
```

So playing around for a while, I started to see the same behavior as you. I could press `A` twice and two votes were sent, one to upvote and one to clear. But after that, pressing `A` stopped sending requests to reddit. Other times, there was a large delay between when I pressed the key and when the request was sent. My hunch is that this has something to do with how PRAW generates requests. Not sure though.

**Comment by michael-lazar** [comment]
You might be able to log the request json data as well
http://stackoverflow.com/questions/16337511/log-all-requests-from-the-python-requests-module

**Comment by michael-lazar** [comment]
Any progress on this?

**Comment by michael-lazar** [comment]
I went ahead and implemented this myself. a58d7ef

**Comment by mekhami** [comment]
Excellent, sorry, I got swamped in work.
