### ISSUE TITLE
Unable to vote on post when viewing comments

### ISSUE THREAD

**Issue by CaptSpify** [michael-lazar/rtv#90]
I'm unable to upvote/downvote the post when viewing the comments. I see this in the log:

DEBUG:requests.packages.urllib3.connectionpool:"POST /api/vote/.json HTTP/1.1" 200 2

Let me know if any questions.

**Comment by michael-lazar** [comment]
When you say unable to vote, do you mean that it crashes the program or that nothing happens? If you're verifying with an open web browser, sometimes it takes 10-30 seconds or so to show up.

**Comment by CaptSpify** [comment]
Nothing seems to happen. You are correct in that it just takes a bit for it to show up. I think the issue is also that there is no vote indicator inside the comment-view for the post itself.

Thanks

**Comment by michael-lazar** [comment]
That makes sense. I think it would be a worthwhile addition to add a vote indicator to the post.

**Comment by Brobin** [comment]
Yeah, I noticed it wasn't there today when I did the nsfw label.
