### ISSUE TITLE
Long selfposts truncated

### ISSUE THREAD

**Issue by adnidor** [michael-lazar/rtv#93]
If I view a selfpost too long to fit on the screen, it is not possible to scroll.

As I mainly read the "tales subreddits", this is pretty bad.

Not sure if bug or feature request

**Comment by Brobin** [comment]
Originally, it didn't display any content. The truncation was put in as a workaround. Since the post is one "cursor" element when navigating, it would probably take some refactoring to split it into a couple elements when it's too long.

**Comment by adnidor** [comment]
What about adding a function to view the content with 'less'?

**Comment by florianbeer** [comment]
:+1: for the idea to read long posts with less. Although I'd prefer it to just respect $PAGER and use that.

**Comment by michael-lazar** [comment]
Do you guys mean temporarily suspending the program and switching to the terminal, or somehow integrating the `less` command into the curses window? Any examples of other applications that do this?

**Comment by florianbeer** [comment]
I was thinking about something similar to how commenting works.
If you expand (right cursor key or "l") the initial long posting it opens up your pager with the whole text. Closing the pager returns you to your previous view within rtv.

I am no Python programmer, so I can't offer any tips. A quick google search turned up this: http://chase-seibert.github.io/blog/2012/10/31/python-fork-exec-vim-raw-input.html

**Comment by adnidor** [comment]
Thats what I had in mind.
I'll try to implement this, but I don't have much experience with python, so I can't tell how long it takes.

**Comment by michael-lazar** [comment]
Go for it! Let me know if you have any questions

**Comment by imoran21** [comment]
Any update on this issue? If not was thinking about take a crack at this.

**Comment by michael-lazar** [comment]
Hi imoran21, thanks for offering to contribute! You're more than welcome to take this on.

The only suggestion I have is the same one I made here https://github.com/michael-lazar/rtv/issues/64. I'm currently in the middle of a large refactoring effort, see https://github.com/michael-lazar/rtv/tree/future_work.  I would suggest holding off until that gets merged so that you don't end up working off of a stale version. If all goes well it should be ready by next week.

**Comment by imoran21** [comment]
@michael-lazar thanks, I will hold off until that is complete!

**Comment by michael-lazar** [comment]
Hey, FYI I just merged everything into master. I'll be doing a lot of testing over the next couple of days, but will only be pushing bugfixes. You're good to go now if you want to start working on this.

**Comment by michael-lazar** [comment]
Done! If you press "l" or "right" the comment/submission will open with the PAGER.
