### ISSUE TITLE
HTML encoded characters in posts and comments

### ISSUE THREAD

**Issue by florianbeer** [michael-lazar/rtv#96]
I am seeing a lot of HTML encoded chars e.g. `&gt;` instead of `>`.
Couldn't you run the text through HTMLParser from the standard lib to improve on that?
http://docs.python.org/library/htmlparser.html

**Comment by Brobin** [comment]
This might be the same issue found in #91

**Comment by michael-lazar** [comment]
^ what he said. All HTML decoding is currently handled by praw, which is already using python's htmlparser internally.

**Comment by florianbeer** [comment]
So there is no / wont be any fix for this issue?
Or would it have to be addressed upstream (I am not familiar with praw)?

**Comment by Brobin** [comment]
Yeah, there's nothing we can do about it. It's an issue with reddit's API, not with praw.

They are returning `lt;` instead of `&lt;`, so it's not being html escaped.

**Comment by michael-lazar** [comment]
If you want to follow up on this I would suggest posting on the praw issue board. They're more knowledgeable about reddit's API in general and may be able to suggest a better solution.

**Comment by florianbeer** [comment]
Alright, thanks for letting me now!
