### ISSUE TITLE
browser not opened when pressing enter or 'o'

### ISSUE THREAD

**Issue by nedson** [michael-lazar/rtv#98]
My web browser (w3m) is not opened when I press o or enter.The link changes color, but nothing happens. I have confirmed that w3m is the default system browser - in fact, at the moment it is the only browser installed. 

Any suggestions? What am I missing?

**Comment by michael-lazar** [comment]
I don't think that the current implementation will work for terminal based browsers. What we're currently doing is opening a new subprocess in the background every time you press `o`. This allows you to open several tabs without having to block the RTV window and wait for the tabs to be closed. 

I think you raise a good point though, we really should support w3m and similar programs. For terminal browsers we would need to temporarily halt the curses program, similar to how the text editor currently works.

**Comment by nedson** [comment]
This would make sense since this is a terminal based Reddit app, I'm sure many folks spend a lot of time wrangling servers and would appreciate not having to open a browser to view an article.

**Comment by michael-lazar** [comment]
Fixed in 1b6fed2. 

You can now set a default browser using the ``$BROWSER`` variable. If ``$BROWSER`` points to a terminal-based application, or RTV detects that you are running without a display, it will attempt to open the browser inside of the terminal. Please let me know if this works out for you.

**Comment by nedson** [comment]
Awesome!!!!! I'm getting it setup now...Thank you!~
